# Generated by Django 5.2.6 on 2025-09-30 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0001_initial'),
        ('survey', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyresponse',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='allow_anonymous',
            field=models.BooleanField(default=False, verbose_name='Allow anonymous participation (without login)'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If the question is required', verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='order',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='surveyquestionoption',
            name='order',
            field=models.IntegerField(default=-1, verbose_name='Order'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent__isnull', False)), fields=('survey', 'respondent'), name='unique_survey_user'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent__isnull', True), ('session_key__isnull', False)), fields=('survey', 'session_key'), name='unique_survey_session'),
        ),
    ]
