# Generated by Django 5.2.2 on 2025-07-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        ('survey', '0002_alter_survey_end_date_alter_survey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestionoption',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
    ]
