# Generated by Django 5.2.7 on 2025-10-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='responses_are_anonymous',
            field=models.BooleanField(default=False, help_text='Do not save or display respondent names', verbose_name='Anonymous responses'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='allow_anonymous',
            field=models.BooleanField(default=False, verbose_name='Allow participation without login'),
        ),
    ]
