# Generated by Django 5.2.7 on 2025-10-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_responses_are_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='responses_are_anonymous',
            field=models.BooleanField(default=False, verbose_name='Responses are anonymous'),
        ),
    ]
