# Generated by Django 5.2.2 on 2025-08-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        ('survey', '0001_squashed_0003_survey_org_surveyanswer_org_surveyquestion_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='surveyquestionoption',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
    ]
