# Generated by Django 6.0.4 on 2026-04-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_survey_responses_are_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateField(blank=True, help_text='After this date the survey is not available', null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(blank=True, help_text='Before this date the survey is not available', null=True, verbose_name='Start date'),
        ),
    ]
