# Generated by Django 6.0.5 on 2026-07-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_survey_end_date_alter_survey_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='responses_are_public',
            field=models.BooleanField(default=False, verbose_name='Responses are public'),
        ),
    ]
