# Generated by Django 6.0.3 on 2026-03-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalchatgroup',
            name='description',
        ),
    ]
