# Generated by Django 6.0.3 on 2026-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatgroup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatdirect',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalchatdirect',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalchatgroup',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
