# Generated by Django 6.0.4 on 2026-05-12 16:15

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatgroup_created_by_historicalchatgroup_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagedirect',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.chat_message_image_upload_to),
        ),
        migrations.AddField(
            model_name='chatmessagedirect',
            name='image_identifier',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chatmessagegroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.chat_message_image_upload_to),
        ),
        migrations.AddField(
            model_name='chatmessagegroup',
            name='image_identifier',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalchatmessagedirect',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalchatmessagedirect',
            name='image_identifier',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalchatmessagegroup',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalchatmessagegroup',
            name='image_identifier',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
