# Generated by Django 6.0.5 on 2026-06-30 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0029_alter_ampel2_options_and_more'),
        ('chat', '0005_chatmessagedirect_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagedirect',
            name='answer_to_ampel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.ampel2'),
        ),
        migrations.AddField(
            model_name='historicalchatmessagedirect',
            name='answer_to_ampel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.ampel2'),
        ),
    ]
