# Generated by Django 6.0.5 on 2026-07-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessagedirect_answer_to_ampel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagedirect',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessagegroup',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalchatmessagedirect',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalchatmessagegroup',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
