# Generated by Django 6.0.4 on 2026-06-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Global', '0029_alter_ampel2_options_and_more'),
        ('ORG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnSigninUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstellt am')),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.einsatzland2', verbose_name='Land')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('person_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Global.personcluster', verbose_name='Benutzergruppe')),
            ],
            options={
                'verbose_name': 'Eigenes Registrieren',
                'verbose_name_plural': 'Eigenes Registrieren',
            },
        ),
    ]
