# Generated by Django 5.2.2 on 2025-07-03 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BW', '0020_bewerber_endbewertung_bewerber_first_wish_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
        migrations.CreateModel(
            name='Einheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurzname')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
            },
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Frage')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Erklärung (Optional)')),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
            },
        ),
        migrations.CreateModel(
            name='Fragekategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurzname')),
            ],
            options={
                'verbose_name': 'Fragekategorie',
                'verbose_name_plural': 'Fragekategorien',
            },
        ),
        migrations.CreateModel(
            name='Bewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bewertung', models.IntegerField(verbose_name='Bewertung')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt bearbeitet')),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BW.bewerber', verbose_name='Freiwillige:r')),
                ('bewerter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teammitglied')),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.einheit', verbose_name='Einheit')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.frage', verbose_name='Frage')),
            ],
            options={
                'verbose_name': 'Bewertung',
                'verbose_name_plural': 'Bewertungen',
            },
        ),
        migrations.AddField(
            model_name='frage',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.fragekategorie', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Zuletzt bearbeitet')),
                ('show_at_presentation', models.BooleanField(default=True, verbose_name='Bei Präsentation zeigen')),
                ('show_name_at_presentation', models.BooleanField(default=True, verbose_name='Namen anzeigen')),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BW.bewerber', verbose_name='Freiwillige:r')),
                ('bewerter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teammitglied')),
                ('einheit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.einheit', verbose_name='Einheit')),
                ('kategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seminar.fragekategorie', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
            },
        ),
    ]
