# Generated by Django 5.2.7 on 2025-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='deadline_end',
            field=models.DateTimeField(blank=True, help_text='Die Endzeit des Seminars, bis zu welcher die Bewerber:innen für die Auswahl des Einsatzlandes ihre Auswahl treffen müssen.', null=True, verbose_name='Länderwahl Ende'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='deadline_start',
            field=models.DateTimeField(blank=True, help_text='Die Startzeit des Seminars, ab welcher die Bewerber:innen für die Auswahl des Einsatzlandes beginnen können.', null=True, verbose_name='Länderwahl Start'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(help_text='Die Beschreibung des Seminars, die Bewerber:innen und Teammitglieder beim Start des Seminars sehen.', verbose_name='Seminar Beschreibung'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='name',
            field=models.CharField(help_text='Der Name des Seminars, der Bewerber:innen und Teammitglieder beim Start des Seminars sehen.', max_length=200, verbose_name='Seminarname'),
        ),
    ]
