# Generated by Django 5.2.2 on 2025-07-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline_start', models.DateTimeField(verbose_name='Deadline Start')),
                ('deadline_end', models.DateTimeField(verbose_name='Deadline Ende')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Seminar',
                'verbose_name_plural': 'Seminare',
            },
        ),
        migrations.DeleteModel(
            name='DeadlineDateTime',
        ),
        migrations.AddField(
            model_name='bewertung',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='einheit',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frage',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fragekategorie',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kommentar',
            name='org',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
    ]
