# Generated by Django 5.2.2 on 2025-07-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_seminar_delete_deadlinedatetime_bewertung_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='deadline_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline Ende'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='deadline_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline Start'),
        ),
    ]
