# Generated by Django 5.2.7 on 2025-10-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_alter_seminar_deadline_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='seminar_end',
            field=models.DateField(blank=True, help_text='Die Enddatum des Seminars.', null=True, verbose_name='Seminar Ende'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='seminar_start',
            field=models.DateField(blank=True, help_text='Die Startdatum des Seminars.', null=True, verbose_name='Seminar Start'),
        ),
    ]
