# Generated by Django 5.2.8 on 2025-11-10 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0006_remove_bewerber_gegenstand_and_more'),
        ('seminar', '0003_seminar_seminar_end_seminar_seminar_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='bewerber',
            field=models.ManyToManyField(blank=True, related_name='seminar_bewerber', to='BW.bewerber', verbose_name='Bewerber:innen'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='verschwiegenheit_von_user',
            field=models.ManyToManyField(blank=True, related_name='verschwiegenheit_von_user', to=settings.AUTH_USER_MODEL, verbose_name='Verschwiegenheit von User'),
        ),
    ]
