# Generated by Django 5.2.2 on 2025-07-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        ('seminar', '0003_alter_seminar_deadline_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation'),
        ),
    ]
