# Generated by Django 5.2.2 on 2025-07-10 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_seminar_verschwiegenheit_von_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='verschwiegenheit_von_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Verschwiegenheit von User'),
        ),
    ]
