# Generated by Django 5.2.2 on 2025-08-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        ('seminar', '0001_squashed_0006_alter_seminar_verschwiegenheit_von_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewertung',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='einheit',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='frage',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='fragekategorie',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='kommentar',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
    ]
