# Generated by Django 5.2.2 on 2025-09-05 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Global', '0001_initial'),
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFileQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Der Name der Datei, die der Bewerber:in hochladen muss.', max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Die Beschreibung der Datei, die der Bewerber:in hochladen muss.', null=True, verbose_name='Beschreibung')),
                ('order', models.IntegerField(blank=True, help_text='Die Position der Datei in der Bewerbung. Wenn leer, wird hinten eingefügt.', null=True, verbose_name='Position')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Bewerbungsdatei',
                'verbose_name_plural': 'Bewerbungsdateien',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='bewerbung/', verbose_name='Datei')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
                ('file_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BW.applicationfilequestion', verbose_name='Datei')),
            ],
            options={
                'verbose_name': 'Bewerbungsdatei',
                'verbose_name_plural': 'Bewerbungsdateien',
            },
        ),
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Die Frage, die der Bewerber:in beantworten soll.', verbose_name='Frage')),
                ('choices', models.TextField(blank=True, help_text='Kommagetrennte Liste von Auswahlmöglichkeiten, die der Bewerber:in auswählen kann. Wenn leer, wird die Antwort als Textfeld angezeigt.', null=True, verbose_name='Auswahlmöglichkeiten')),
                ('description', models.TextField(blank=True, help_text='Die Beschreibung der Frage, die der Bewerber:in beantworten soll.', null=True, verbose_name='Beschreibung')),
                ('order', models.IntegerField(blank=True, help_text='Die Position der Frage in der Bewerbung. Wenn leer, wird hinten eingefügt.', null=True, verbose_name='Position')),
                ('max_length', models.IntegerField(blank=True, default=1000, help_text='Die maximale Länge der Antwort.', null=True, verbose_name='Maximale Länge')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Bewerbungsfrage',
                'verbose_name_plural': 'Bewerbungsfragen',
                'ordering': ['order'],
                'unique_together': {('org', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, help_text='Die Antwort, die der Bewerber:in gegeben hat.', null=True, verbose_name='Antwort')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
                ('question', models.ForeignKey(help_text='Die Frage, die der Bewerber:in beantworten soll.', on_delete=django.db.models.deletion.CASCADE, to='BW.applicationquestion', verbose_name='Frage')),
            ],
            options={
                'verbose_name': 'Bewerbungsantwort',
                'verbose_name_plural': 'Bewerbungsantworten',
            },
        ),
        migrations.CreateModel(
            name='ApplicationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.TextField(help_text='Die Begrüßung, die der Bewerber:in beim Start der Bewerbung sieht.', verbose_name='Begrüßung')),
                ('footer', models.TextField(help_text='Die Fußzeile, die der Bewerber:in am Ende der Bewerbung sieht.', verbose_name='Fußzeile')),
                ('deadline', models.DateField(blank=True, help_text='Die Abgabefrist, bis zu welcher die Bewerbung abgeschlossen werden muss.', null=True, verbose_name='Abgabefrist')),
                ('welcome_account_create', models.TextField(blank=True, help_text='Die Begrüßung, die der Bewerber:in beim Erstellen des Kontos sieht.', null=True, verbose_name='Begrüßung bei Kontoerstellung')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Bewerbungstext',
                'verbose_name_plural': 'Bewerbungstexte',
            },
        ),
        migrations.CreateModel(
            name='Bewerber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Verifikationstoken')),
                ('abgeschlossen', models.BooleanField(default=False, verbose_name='Abgeschlossen')),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('status', models.CharField(blank=True, choices=[('red', 'Rot'), ('yellow', 'Gelb'), ('green', 'Grün')], max_length=20, null=True, verbose_name='Status')),
                ('status_comment', models.TextField(blank=True, help_text='Der Kommentar, der dem Status zugeordnet wird.', null=True, verbose_name='Statuskommentar')),
                ('gegenstand', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gegenstand')),
                ('first_wish', models.CharField(blank=True, max_length=200, null=True, verbose_name='Erstwunsch')),
                ('second_wish', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zweitwunsch')),
                ('third_wish', models.CharField(blank=True, max_length=200, null=True, verbose_name='Drittwunsch')),
                ('no_wish', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nicht')),
                ('endbewertung', models.CharField(blank=True, choices=[('G', 'Geeignet'), ('B', 'Bedingt geeignet'), ('N', 'Nicht geeignet')], max_length=1, null=True, verbose_name='Endbewertung')),
                ('note', models.FloatField(blank=True, null=True, verbose_name='Note')),
                ('kommentar_zusammenfassung', models.TextField(blank=True, null=True, verbose_name='Zusammenfassung der Kommentare')),
                ('accessible_by_team_member', models.ManyToManyField(blank=True, help_text='Die Teammitglieder/Ehemaligen, die auf die Bewerbung des Bewerbers:in zugreifen können.', related_name='accessible_applications', to=settings.AUTH_USER_MODEL, verbose_name='Zugriff auf Bewerbung')),
                ('first_wish_einsatzland', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_wish_einsatzland', to='Global.einsatzland2', verbose_name='Erstwunsch Einsatzland')),
                ('first_wish_einsatzstelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Erstwunsch Einsatzstelle')),
                ('interview_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interview_1', to=settings.AUTH_USER_MODEL, verbose_name='Interviewperson 1')),
                ('interview_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interview_2', to=settings.AUTH_USER_MODEL, verbose_name='Interviewperson 2')),
                ('no_wish_einsatzland', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_wish_einsatzland', to='Global.einsatzland2', verbose_name='Nicht Einsatzland')),
                ('no_wish_einsatzstelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Nicht Einsatzstelle')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('second_wish_einsatzland', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_wish_einsatzland', to='Global.einsatzland2', verbose_name='Zweitwunsch Einsatzland')),
                ('second_wish_einsatzstelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Zweitwunsch Einsatzstelle')),
                ('third_wish_einsatzland', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_wish_einsatzland', to='Global.einsatzland2', verbose_name='Drittwunsch Einsatzland')),
                ('third_wish_einsatzstelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Drittwunsch Einsatzstelle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
                ('zuteilung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zuteilung', to='Global.einsatzstelle2', verbose_name='Zuteilung')),
            ],
            options={
                'verbose_name': 'Bewerber:in',
                'verbose_name_plural': 'Bewerber:innen',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
