# Generated by Django 5.2.6 on 2025-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfilequestion',
            name='is_profile_picture',
            field=models.BooleanField(default=False, help_text='Dieses Bild wird als Profilbild des Bewerbers:in angezeigt.', verbose_name='Ist Profilbild'),
        ),
    ]
