# Generated by Django 5.2.1 on 2025-05-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0002_applicationfooter_applicationwelcome'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationwelcome',
            name='org',
        ),
        migrations.CreateModel(
            name='ApplicationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome', models.TextField(verbose_name='Begrüßung')),
                ('footer', models.TextField(verbose_name='Fußzeile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ApplicationFooter',
        ),
        migrations.DeleteModel(
            name='ApplicationWelcome',
        ),
    ]
