# Generated by Django 5.2.6 on 2025-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0002_applicationfilequestion_is_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfilequestion',
            name='required',
            field=models.BooleanField(default=True, help_text='Diese Datei ist nicht optional und muss bei der Bewerbung hochgeladen werden.', verbose_name='Benötigt'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='welcome',
            field=models.TextField(help_text='Die Begrüßung, die der Bewerber:in beim Start der Bewerbung sieht.', verbose_name='Willkommensnachricht'),
        ),
    ]
