# Generated by Django 5.2.7 on 2025-10-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0003_applicationfilequestion_required_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bewerber',
            options={},
        ),
        migrations.AddField(
            model_name='bewerber',
            name='application_pdf',
            field=models.FileField(blank=True, help_text='Falls die Bewerbung per Mail versendet wurde, kann hier das PDF der Bewerbung hochgeladen werden.', null=True, upload_to='bewerbung/', verbose_name='PDF der Bewerbung'),
        ),
    ]
