# Generated by Django 5.2.1 on 2025-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0004_bewerber'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationanswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bewerbung/', verbose_name='Datei'),
        ),
        migrations.AddField(
            model_name='applicationquestion',
            name='answer_type',
            field=models.CharField(choices=[('t', 'Text'), ('f', 'Datei')], default='t', max_length=255, verbose_name='Antworttyp'),
        ),
    ]
