# Generated by Django 5.2.7 on 2025-10-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0004_alter_bewerber_options_bewerber_application_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bewerber',
            options={'verbose_name': 'Bewerber:in', 'verbose_name_plural': 'Bewerber:innen'},
        ),
    ]
