# Generated by Django 5.2.7 on 2025-10-26 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0005_alter_bewerber_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewerber',
            name='gegenstand',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='interview_1',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='interview_2',
        ),
        migrations.AddField(
            model_name='bewerber',
            name='interview_persons',
            field=models.ManyToManyField(blank=True, help_text='Die Personen, die das Interview mit dem Bewerber:in geführt haben.', related_name='interview_persons', to=settings.AUTH_USER_MODEL, verbose_name='Interviewpersonen/Ehemalige'),
        ),
    ]
