# Generated by Django 5.2.1 on 2025-05-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0005_applicationanswer_file_and_more'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationquestion',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='applicationanswer',
            name='file',
        ),
        migrations.RemoveField(
            model_name='applicationquestion',
            name='answer_type',
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reihenfolge'),
        ),
        migrations.CreateModel(
            name='ApplicationFileQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Reihenfolge')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='bewerbung/', verbose_name='Datei')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
                ('file_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BW.applicationfilequestion', verbose_name='Datei')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
