# Generated by Django 5.2.1 on 2025-05-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0006_alter_applicationquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfilequestion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
    ]
