# Generated by Django 5.2.8 on 2025-11-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0006_remove_bewerber_gegenstand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerber',
            name='reaktion_auf_zuteilung',
            field=models.TextField(blank=True, help_text='Die Reaktion auf die Zuteilung.', null=True, verbose_name='Reaktion auf Zuteilung'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='zuteilung_freigegeben',
            field=models.BooleanField(default=False, help_text='Gibt an, ob die Zuteilung freigegeben wurde.', verbose_name='Zuteilung freigegeben'),
        ),
    ]
