# Generated by Django 5.2.1 on 2025-05-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0007_applicationfilequestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerber',
            name='status',
            field=models.CharField(choices=[('G', 'Grün'), ('Y', 'Gelb'), ('R', 'Rot')], default='G', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='max_length',
            field=models.IntegerField(blank=True, default=1000, null=True, verbose_name='Maximale Länge'),
        ),
    ]
