# Generated by Django 5.2.8 on 2025-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0007_bewerber_reaktion_auf_zuteilung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerber',
            name='reaktion_auf_zuteilung',
            field=models.TextField(blank=True, help_text='Die Reaktion durch den Bewerber:in auf die Zuteilung.', null=True, verbose_name='Reaktion auf Zuteilung'),
        ),
        migrations.AlterField(
            model_name='bewerber',
            name='zuteilung_freigegeben',
            field=models.BooleanField(default=False, help_text='Gibt an, ob die Zuteilung zur Einsatzstelle für den Bewerber:in sichtbar ist.', verbose_name='Zuteilung freigegeben'),
        ),
    ]
