# Generated by Django 6.0.4 on 2026-06-19 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0008_alter_bewerber_reaktion_auf_zuteilung_and_more'),
        ('Global', '0029_alter_ampel2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtext',
            name='person_cluster',
            field=models.ForeignKey(help_text='Die Benutzergruppe, der Bewerber:innen zugeordnet werden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_texts', to='Global.personcluster', verbose_name='Bewerbergruppe'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='deadline',
            field=models.DateField(blank=True, help_text='Nach diesem Datum können keine Bewerbungen mehr abgegeben werden.', null=True, verbose_name='Abgabefrist'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='footer',
            field=models.TextField(help_text='Die Fußzeile, die am Ende der Bewerbung angezeigt wird.', verbose_name='Fußzeile'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='welcome',
            field=models.TextField(help_text='Die Begrüßung, die beim Start der Bewerbung angezeigt wird.', verbose_name='Willkommensnachricht'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='welcome_account_create',
            field=models.TextField(blank=True, help_text='Die Begrüßung, die beim Erstellen des Kontos angezeigt wird.', null=True, verbose_name='Begrüßung bei Kontoerstellung'),
        ),
    ]
