# Generated by Django 5.2.1 on 2025-05-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0008_bewerber_status_alter_applicationquestion_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerber',
            name='status',
            field=models.CharField(blank=True, choices=[('green', 'Grün'), ('yellow', 'Gelb'), ('red', 'Rot')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
