# Generated by Django 5.2.1 on 2025-05-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0009_alter_bewerber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerber',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Verifikationstoken'),
        ),
    ]
