# Generated by Django 5.2.1 on 2025-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0010_bewerber_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtext',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Abgabefrist'),
        ),
    ]
