# Generated by Django 6.0.5 on 2026-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0010_applicationanswerfile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationanswer',
            name='is_done',
            field=models.BooleanField(db_default=False, default=False, help_text='Vom Bewerber als erledigt markiert.', verbose_name='Erledigt'),
        ),
    ]
