# Generated by Django 5.2.1 on 2025-05-16 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0011_applicationtext_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationanswer',
            options={'verbose_name': 'Bewerbungsantwort', 'verbose_name_plural': 'Bewerbungsantworten'},
        ),
        migrations.AlterModelOptions(
            name='applicationanswerfile',
            options={'verbose_name': 'Bewerbungsdatei', 'verbose_name_plural': 'Bewerbungsdateien'},
        ),
        migrations.AlterModelOptions(
            name='applicationfilequestion',
            options={'ordering': ['order'], 'verbose_name': 'Bewerbungsdatei', 'verbose_name_plural': 'Bewerbungsdateien'},
        ),
        migrations.AlterModelOptions(
            name='applicationquestion',
            options={'ordering': ['order'], 'verbose_name': 'Bewerbungsfrage', 'verbose_name_plural': 'Bewerbungsfragen'},
        ),
        migrations.AlterModelOptions(
            name='applicationtext',
            options={'verbose_name': 'Bewerbungstext', 'verbose_name_plural': 'Bewerbungstexte'},
        ),
        migrations.AlterModelOptions(
            name='bewerber',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Bewerber:in', 'verbose_name_plural': 'Bewerber:innen'},
        ),
        migrations.AlterField(
            model_name='applicationanswer',
            name='answer',
            field=models.TextField(blank=True, help_text='Die Antwort, die der Bewerber:in gegeben hat.', null=True, verbose_name='Antwort'),
        ),
        migrations.AlterField(
            model_name='applicationanswer',
            name='question',
            field=models.ForeignKey(help_text='Die Frage, die der Bewerber:in beantworten soll.', on_delete=django.db.models.deletion.CASCADE, to='BW.applicationquestion', verbose_name='Frage'),
        ),
        migrations.AlterField(
            model_name='applicationfilequestion',
            name='description',
            field=models.TextField(blank=True, help_text='Die Beschreibung der Datei, die der Bewerber:in hochladen muss.', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='applicationfilequestion',
            name='name',
            field=models.CharField(help_text='Der Name der Datei, die der Bewerber:in hochladen muss.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='applicationfilequestion',
            name='order',
            field=models.IntegerField(blank=True, help_text='Die Position der Datei in der Bewerbung. Wenn leer, wird hinten eingefügt.', null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='max_length',
            field=models.IntegerField(blank=True, default=1000, help_text='Die maximale Länge der Antwort.', null=True, verbose_name='Maximale Länge'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='order',
            field=models.IntegerField(blank=True, help_text='Die Position der Frage in der Bewerbung. Wenn leer, wird hinten eingefügt.', null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='question',
            field=models.TextField(help_text='Die Frage, die der Bewerber:in beantworten soll.', verbose_name='Frage'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='deadline',
            field=models.DateField(blank=True, help_text='Die Abgabefrist, bis zu welcher die Bewerbung abgeschlossen werden muss.', null=True, verbose_name='Abgabefrist'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='footer',
            field=models.TextField(help_text='Die Fußzeile, die der Bewerber:in am Ende der Bewerbung sieht.', verbose_name='Fußzeile'),
        ),
        migrations.AlterField(
            model_name='applicationtext',
            name='welcome',
            field=models.TextField(help_text='Die Begrüßung, die der Bewerber:in beim Start der Bewerbung sieht.', verbose_name='Begrüßung'),
        ),
    ]
