# Generated by Django 5.2.1 on 2025-05-16 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0012_alter_applicationanswer_options_and_more'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationquestion',
            unique_together={('org', 'order')},
        ),
    ]
