# Generated by Django 5.2.1 on 2025-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0013_alter_applicationquestion_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtext',
            name='welcome_account_create',
            field=models.TextField(blank=True, help_text='Die Begrüßung, die der Bewerber:in beim Erstellen des Kontos sieht.', null=True, verbose_name='Begrüßung bei Kontoerstellung'),
        ),
    ]
