# Generated by Django 5.2.1 on 2025-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0014_applicationtext_welcome_account_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='description',
            field=models.TextField(blank=True, help_text='Die Beschreibung der Frage, die der Bewerber:in beantworten soll.', null=True, verbose_name='Beschreibung'),
        ),
    ]
