# Generated by Django 5.2.1 on 2025-06-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0015_applicationquestion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='choices',
            field=models.TextField(blank=True, help_text='Kommagetrennte Liste von Auswahlmöglichkeiten, die der Bewerber:in auswählen kann. Wenn leer, wird die Antwort als Textfeld angezeigt.', null=True, verbose_name='Auswahlmöglichkeiten'),
        ),
    ]
