# Generated by Django 5.2.1 on 2025-06-06 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0016_applicationquestion_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerber',
            name='accessible_by_team_member',
            field=models.ManyToManyField(blank=True, help_text='Die Teammitglieder/Ehemaligen, die auf die Bewerbung des Bewerbers:in zugreifen können.', related_name='accessible_applications', to=settings.AUTH_USER_MODEL, verbose_name='Zugriff auf Bewerbung'),
        ),
    ]
