# Generated by Django 5.2.1 on 2025-06-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0017_bewerber_accessible_by_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerber',
            name='status_comment',
            field=models.TextField(blank=True, help_text='Der Kommentar, der dem Status zugeordnet wird.', null=True, verbose_name='Statuskommentar'),
        ),
    ]
