# Generated by Django 5.2.2 on 2025-06-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0018_bewerber_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerber',
            name='status',
            field=models.CharField(blank=True, choices=[('red', 'Rot'), ('yellow', 'Gelb'), ('green', 'Grün')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
