# Generated by Django 5.2.2 on 2025-07-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0020_bewerber_endbewertung_bewerber_first_wish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewerber',
            name='endbewertung',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='first_wish',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='first_wish_einsatzland',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='first_wish_einsatzstelle',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='gegenstand',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='interview_1',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='interview_2',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='kommentar_zusammenfassung',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='no_wish',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='no_wish_einsatzland',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='no_wish_einsatzstelle',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='note',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='second_wish',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='second_wish_einsatzland',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='second_wish_einsatzstelle',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='third_wish',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='third_wish_einsatzland',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='third_wish_einsatzstelle',
        ),
        migrations.RemoveField(
            model_name='bewerber',
            name='zuteilung',
        ),
    ]
