# Generated by Django 5.2.2 on 2025-07-31 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0023_remove_bewerber_endbewertung_and_more'),
        ('Global', '0064_einsatzstelle2_max_freiwillige_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bewerber',
            name='endbewertung',
            field=models.CharField(blank=True, choices=[('G', 'Geeignet'), ('B', 'Bedingt geeignet'), ('N', 'Nicht geeignet')], max_length=1, null=True, verbose_name='Endbewertung'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='first_wish',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Erstwunsch'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='first_wish_einsatzland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_wish_einsatzland', to='Global.einsatzland2', verbose_name='Erstwunsch Einsatzland'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='first_wish_einsatzstelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Erstwunsch Einsatzstelle'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='gegenstand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Gegenstand'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='interview_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interview_1', to=settings.AUTH_USER_MODEL, verbose_name='Interviewperson 1'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='interview_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interview_2', to=settings.AUTH_USER_MODEL, verbose_name='Interviewperson 2'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='kommentar_zusammenfassung',
            field=models.TextField(blank=True, null=True, verbose_name='Zusammenfassung der Kommentare'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='no_wish',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nicht'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='no_wish_einsatzland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_wish_einsatzland', to='Global.einsatzland2', verbose_name='Nicht Einsatzland'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='no_wish_einsatzstelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Nicht Einsatzstelle'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='note',
            field=models.FloatField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='second_wish',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Zweitwunsch'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='second_wish_einsatzland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_wish_einsatzland', to='Global.einsatzland2', verbose_name='Zweitwunsch Einsatzland'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='second_wish_einsatzstelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Zweitwunsch Einsatzstelle'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='third_wish',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Drittwunsch'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='third_wish_einsatzland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_wish_einsatzland', to='Global.einsatzland2', verbose_name='Drittwunsch Einsatzland'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='third_wish_einsatzstelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_wish_einsatzstelle', to='Global.einsatzstelle2', verbose_name='Drittwunsch Einsatzstelle'),
        ),
        migrations.AddField(
            model_name='bewerber',
            name='zuteilung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zuteilung', to='Global.einsatzstelle2', verbose_name='Zuteilung'),
        ),
    ]
