# Generated by Django 5.2.8 on 2025-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ehemalige', '0001_initial'),
        ('Global', '0015_alter_aufgabe2_visible_by_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehemalige',
            name='land',
            field=models.ManyToManyField(blank=True, null=True, to='Global.einsatzland2', verbose_name='Länder'),
        ),
    ]
