"""
Django settings for FWMsg project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import json
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# SECRETS CONFIGURATION
# =============================================================================


def load_secrets():
    """Load secrets from .secrets.json file."""
    secrets_file = BASE_DIR / "FWMsg" / ".secrets.json"

    try:
        with open(secrets_file) as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"WARNING: {secrets_file} not found. Using default settings.")
        return {}
    except json.JSONDecodeError:
        print(f"ERROR: Invalid JSON in {secrets_file}")
        return {}


secrets = load_secrets()

# =============================================================================
# CORE DJANGO SETTINGS
# =============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secrets.get(
    "secret_key", "django-insecure-default-key-change-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = secrets.get("debug", True)

# Configure allowed hosts properly - never use ['*'] in production
ALLOWED_HOSTS = secrets.get("allowed_hosts", ["localhost", "127.0.0.1"])

DOMAIN = secrets.get("domain", "localhost")
DOMAIN_HOST = secrets.get("domain_host", "https://localhost")

# =============================================================================
# SECURITY SETTINGS
# =============================================================================

if not DEBUG:
    # Production security settings
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# =============================================================================
# APPLICATION DEFINITION
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "FW.apps.FwConfig",
    "ORG.apps.OrgConfig",
    "Home.apps.HomeConfig",
    "ADMIN.apps.AdminConfig",
    "Global.apps.GlobalConfig",
    "TEAM.apps.TeamConfig",
    "BW.apps.BwConfig",
    "seminar.apps.SeminarConfig",
    "survey.apps.SurveyConfig",
    "widget_tweaks",
    "celery",
    "django_celery_results",
    "simple_history",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "FWMsg.middleware.RequestMiddleware",
    "Global.middleware.OnlineStatusMiddleware",
    "Global.middleware.OfflineStatusMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "FWMsg.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "ORG.views.org_context_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "FWMsg.wsgi.application"

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "django_password_validators.password_character_requirements.password_validation.PasswordCharacterValidator",
        "OPTIONS": {
            "min_length_digit": 1,
            "min_length_alpha": 1,
            "min_length_special": 1,
            "min_length_lower": 1,
            "min_length_upper": 1,
            "special_characters": "~!?@#$%^&*()_+{}\":;'[]",
        },
    },
]

# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "de"

LANGUAGES = [
    ("de", "German"),
    ("en", "English"),
]

TIME_ZONE = "Europe/Berlin"
TIME_INPUT_FORMATS = ["%H:%M", "%H:%M:%S"]
DATE_INPUT_FORMATS = ["%d.%m.%Y", "%Y-%m-%d"]
DATETIME_INPUT_FORMATS = ["%d.%m.%Y %H:%M", "%Y-%m-%d %H:%M"]

USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# =============================================================================
# STATIC FILES CONFIGURATION
# =============================================================================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = [
    BASE_DIR / "FW/fw-static",
    BASE_DIR / "ORG/org-static",
    BASE_DIR / "Global/global-static",
    BASE_DIR / "TEAM/team-static",
    BASE_DIR / "logos",
]

# =============================================================================
# MEDIA FILES CONFIGURATION
# =============================================================================

MEDIA_ROOT_NAME = "media"
MEDIA_ROOT = BASE_DIR / MEDIA_ROOT_NAME

# =============================================================================
# AUTHENTICATION CONFIGURATION
# =============================================================================

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/login/"

# =============================================================================
# DJANGO CORE SETTINGS
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# CELERY CONFIGURATION
# =============================================================================

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 15 * 60  # 15 minutes
CELERY_TIMEZONE = "Europe/Berlin"

# =============================================================================
# CSRF CONFIGURATION
# =============================================================================

CSRF_TRUSTED_ORIGINS = secrets.get("csrf_trusted_origins", [])

# =============================================================================
# EMAIL CONFIGURATION
# =============================================================================


def configure_email_settings():
    """Configure email settings from secrets or use defaults."""
    email_config = {
        "SERVER_EMAIL": "noreply@example.com",
        "EMAIL_HOST": "smtp.example.com",
        "EMAIL_PORT": 587,
        "EMAIL_HOST_USER": "notifications@example.com",
        "EMAIL_HOST_PASSWORD": "",
        "EMAIL_USE_TLS": True,
        "EMAIL_USE_SSL": False,
        "ADMINS": [],
        "VAPID_PUBLIC_KEY": "YOUR_VAPID_PUBLIC_KEY",
        "VAPID_PRIVATE_KEY": "YOUR_VAPID_PRIVATE_KEY",
    }

    if secrets:
        email_config.update(
            {
                "SERVER_EMAIL": secrets.get(
                    "server_mail", email_config["SERVER_EMAIL"]
                ),
                "EMAIL_HOST": secrets.get("smtp_server", email_config["EMAIL_HOST"]),
                "EMAIL_PORT": secrets.get("port", email_config["EMAIL_PORT"]),
                "EMAIL_HOST_USER": secrets.get(
                    "sender_email", email_config["EMAIL_HOST_USER"]
                ),
                "EMAIL_HOST_PASSWORD": secrets.get(
                    "password", email_config["EMAIL_HOST_PASSWORD"]
                ),
                "ADMINS": secrets.get("admins", email_config["ADMINS"]),
                "VAPID_PUBLIC_KEY": secrets.get(
                    "vapid_public_key", email_config["VAPID_PUBLIC_KEY"]
                ),
                "VAPID_PRIVATE_KEY": secrets.get(
                    "vapid_private_key", email_config["VAPID_PRIVATE_KEY"]
                ),
            }
        )
    else:
        print("WARNING: .secrets.json not found. Email functionality will not work.")

    return email_config


# Apply email configuration
email_settings = configure_email_settings()
globals().update(email_settings)

MANAGERS = secrets.get("admins", [])

# =============================================================================
# SECRETS FILE TEMPLATE
# =============================================================================

"""
Create a .secrets.json file in the FWMsg directory with the following structure:

{
    "secret_key": "your-secret-key-here",
    "debug": false,
    "allowed_hosts": ["yourdomain.com", "www.yourdomain.com"],
    "server_mail": "noreply@example.com",
    "smtp_server": "smtp.example.com",
    "port": 587,
    "sender_email": "notifications@example.com",
    "password": "your_email_password",
    "vapid_public_key": "YOUR_VAPID_PUBLIC_KEY",
    "vapid_private_key": "YOUR_VAPID_PRIVATE_KEY",
    "admins": [
        ["Admin Name", "admin@example.com"]
    ],
    "csrf_trusted_origins": ["*"],
    "trusted_orgins": ["*"],
    "domain": "example.com",
    "domain_host": "https://example.com",
}

IMPORTANT: Add .secrets.json to .gitignore!
"""
