# Generated by Django 5.2.2 on 2025-09-05 12:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Global', '0001_initial'),
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freiwilliger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_geplant', models.DateField(blank=True, null=True, verbose_name='Start geplant')),
                ('start_real', models.DateField(blank=True, null=True, verbose_name='Start real')),
                ('ende_geplant', models.DateField(blank=True, null=True, verbose_name='Ende geplant')),
                ('ende_real', models.DateField(blank=True, null=True, verbose_name='Ende real')),
                ('einsatzland2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.einsatzland2', verbose_name='Einsatzland')),
                ('einsatzstelle2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.einsatzstelle2', verbose_name='Einsatzstelle')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
            ],
            options={
                'verbose_name': 'Freiwillige:r',
                'verbose_name_plural': 'Freiwillige',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFreiwilliger',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_geplant', models.DateField(blank=True, null=True, verbose_name='Start geplant')),
                ('start_real', models.DateField(blank=True, null=True, verbose_name='Start real')),
                ('ende_geplant', models.DateField(blank=True, null=True, verbose_name='Ende geplant')),
                ('ende_real', models.DateField(blank=True, null=True, verbose_name='Ende real')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('einsatzland2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.einsatzland2', verbose_name='Einsatzland')),
                ('einsatzstelle2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.einsatzstelle2', verbose_name='Einsatzstelle')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
            ],
            options={
                'verbose_name': 'historical Freiwillige:r',
                'verbose_name_plural': 'historical Freiwillige',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
