# Generated by Django 5.1.2 on 2024-11-04 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('mitupload', models.BooleanField(default=False)),
                ('faellig', models.DateField(blank=True, null=True)),
                ('faellig_tage_nach_start', models.IntegerField(blank=True, null=True)),
                ('faellig_tage_vor_ende', models.IntegerField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='Aufgabenprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Aufgabenprofil',
                'verbose_name_plural': 'Aufgabenprofile',
            },
        ),
        migrations.CreateModel(
            name='AufgabenprofilAufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabe')),
                ('aufgabenprofil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabenprofil')),
            ],
            options={
                'verbose_name': 'Aufgabenprofil Aufgabe',
                'verbose_name_plural': 'Aufgabenprofil Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='Bilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
        migrations.CreateModel(
            name='BilderGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bilder/')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Bilder Gallery',
                'verbose_name_plural': 'Bilder Galleries',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Einsatzland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Einsatzland',
                'verbose_name_plural': 'Einsatzländer',
            },
        ),
        migrations.AddField(
            model_name='aufgabenprofil',
            name='einsatzland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzland'),
        ),
        migrations.CreateModel(
            name='Einsatzstelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzland')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Einsatzstelle',
                'verbose_name_plural': 'Einsatzstellen',
            },
        ),
        migrations.AddField(
            model_name='aufgabenprofil',
            name='einsatzstelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzstelle'),
        ),
        migrations.CreateModel(
            name='Entsendeform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Entsendeform',
                'verbose_name_plural': 'Entsendeformen',
            },
        ),
        migrations.CreateModel(
            name='Freiwilliger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('geschlecht', models.CharField(blank=True, choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers'), ('N', 'Keine Angabe')], max_length=1, null=True)),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('strasse', models.CharField(blank=True, max_length=100, null=True)),
                ('plz', models.CharField(blank=True, max_length=10, null=True)),
                ('ort', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_einsatzland', models.CharField(blank=True, max_length=20, null=True)),
                ('start_geplant', models.DateField(blank=True, null=True)),
                ('start_real', models.DateField(blank=True, null=True)),
                ('ende_geplant', models.DateField(blank=True, null=True)),
                ('ende_real', models.DateField(blank=True, null=True)),
                ('entsendeform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.entsendeform')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freiwillige:r',
                'verbose_name_plural': 'Freiwillige',
            },
        ),
        migrations.CreateModel(
            name='Ampel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('G', 'Grün'), ('Y', 'Gelb'), ('R', 'Rot')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('freiwilliger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger')),
            ],
        ),
        migrations.CreateModel(
            name='FreiwilligerAufgaben',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erledigt', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('faellig', models.DateField(blank=True, null=True)),
                ('erledigt_am', models.DateField(blank=True, null=True)),
                ('wiederholung', models.CharField(choices=[('T', 'Täglich'), ('W', 'Wöchentlich'), ('M', 'Monatlich'), ('J', 'Jährlich'), ('N', 'Nicht wiederholen')], max_length=1)),
                ('wiederholung_ende', models.DateField(blank=True, null=True)),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabe')),
                ('freiwilliger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger')),
            ],
            options={
                'verbose_name': 'Freiwilliger Aufgabe',
                'verbose_name_plural': 'Freiwilliger Aufgaben',
            },
        ),
        migrations.CreateModel(
            name='FreiwilligerAufgabenprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabenprofil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabenprofil')),
                ('freiwilliger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger')),
            ],
            options={
                'verbose_name': 'Freiwilliger Aufgabenprofil',
                'verbose_name_plural': 'Freiwilliger Aufgabenprofile',
            },
        ),
        migrations.CreateModel(
            name='FreiwilligerFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='fotos/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('freiwilliger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Freiwilliger Foto',
                'verbose_name_plural': 'Freiwilliger Fotos',
            },
        ),
        migrations.CreateModel(
            name='FreiwilligerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('freiwilligeraufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilligeraufgaben')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Freiwilliger Upload',
                'verbose_name_plural': 'Freiwilliger Uploads',
            },
        ),
        migrations.CreateModel(
            name='Jahrgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateField(blank=True, null=True)),
                ('ende', models.DateField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Jahrgang',
                'verbose_name_plural': 'Jahrgänge',
            },
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='jahrgang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.jahrgang'),
        ),
        migrations.CreateModel(
            name='Kirchenzugehoerigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Kirchenzugehörigkeit',
                'verbose_name_plural': 'Kirchenzugehörigkeiten',
            },
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='kirchenzugehoerigkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.kirchenzugehoerigkeit'),
        ),
        migrations.CreateModel(
            name='Notfallkontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('freiwilliger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Notfallkontakt',
                'verbose_name_plural': 'Notfallkontakte',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
