# Generated by Django 5.1.2 on 2024-11-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildergallery',
            name='bilder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FW.bilder'),
            preserve_default=False,
        ),
    ]
