# Generated by Django 5.1.2 on 2024-11-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0002_bildergallery_bilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildergallery',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='bilder/small/'),
        ),
    ]
