# Generated by Django 5.1.2 on 2024-11-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0003_bildergallery_small_image'),
        ('ORG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatzland',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='einsatzland',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
    ]
