# Generated by Django 5.1.2 on 2024-12-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0004_alter_einsatzland_name_alter_einsatzland_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
