# Generated by Django 5.1.2 on 2024-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0005_ampel_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ampel',
            options={'verbose_name': 'Ampel', 'verbose_name_plural': 'Ampeln'},
        ),
        migrations.AlterField(
            model_name='ampel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
