# Generated by Django 5.1.2 on 2024-12-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0006_alter_ampel_options_alter_ampel_date'),
        ('ORG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation'),
            preserve_default=False,
        ),
    ]
