# Generated by Django 5.1.2 on 2024-12-14 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0007_freiwilligeraufgaben_org'),
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampel',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='ampel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='ampel',
            name='freiwilliger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger', verbose_name='Freiwillige:r'),
        ),
        migrations.AlterField(
            model_name='ampel',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='ampel',
            name='status',
            field=models.CharField(choices=[('G', 'Grün'), ('Y', 'Gelb'), ('R', 'Rot')], max_length=1, verbose_name='Ampelmeldung'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='faellig',
            field=models.DateField(blank=True, null=True, verbose_name='Fällig am'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='faellig_tage_nach_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fällig Tage nach Einsatzstart'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='faellig_tage_vor_ende',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fällig Tage vor Einsatzende'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='mitupload',
            field=models.BooleanField(default=False, verbose_name='Upload möglich'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Aufgabenname'),
        ),
        migrations.AlterField(
            model_name='aufgabe',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='aufgabenprofil',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='aufgabenprofil',
            name='einsatzland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzland', verbose_name='Einsatzland'),
        ),
        migrations.AlterField(
            model_name='aufgabenprofil',
            name='einsatzstelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzstelle', verbose_name='Einsatzstelle'),
        ),
        migrations.AlterField(
            model_name='aufgabenprofil',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Aufgabenprofil-Name'),
        ),
        migrations.AlterField(
            model_name='aufgabenprofil',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='aufgabenprofilaufgabe',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabe', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='aufgabenprofilaufgabe',
            name='aufgabenprofil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabenprofil', verbose_name='Aufgabenprofil'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='titel',
            field=models.CharField(max_length=50, verbose_name='Bildtitel'),
        ),
        migrations.AlterField(
            model_name='bilder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='bildergallery',
            name='bilder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.bilder', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='bildergallery',
            name='image',
            field=models.ImageField(upload_to='bilder/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='bildergallery',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='bildergallery',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='bilder/small/', verbose_name='Kleines Bild'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='einsatzland',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Einsatzland'),
        ),
        migrations.AlterField(
            model_name='einsatzstelle',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzland', verbose_name='Einsatzland'),
        ),
        migrations.AlterField(
            model_name='einsatzstelle',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Einsatzstelle'),
        ),
        migrations.AlterField(
            model_name='einsatzstelle',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='entsendeform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Entsendeform-Name'),
        ),
        migrations.AlterField(
            model_name='entsendeform',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='ende_geplant',
            field=models.DateField(blank=True, null=True, verbose_name='Ende geplant'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='ende_real',
            field=models.DateField(blank=True, null=True, verbose_name='Ende real'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='entsendeform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.entsendeform', verbose_name='Entsendeform'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers'), ('N', 'Keine Angabe')], max_length=1, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='jahrgang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.jahrgang', verbose_name='Jahrgang'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='kirchenzugehoerigkeit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.kirchenzugehoerigkeit', verbose_name='Kirchenzugehörigkeit'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='ort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='phone_einsatzland',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Einsatzland'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='start_geplant',
            field=models.DateField(blank=True, null=True, verbose_name='Start geplant'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='start_real',
            field=models.DateField(blank=True, null=True, verbose_name='Start real'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='strasse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='aufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabe', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='erledigt',
            field=models.BooleanField(default=False, verbose_name='Erledigt'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='erledigt_am',
            field=models.DateField(blank=True, null=True, verbose_name='Erledigt am'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='faellig',
            field=models.DateField(blank=True, null=True, verbose_name='Fällig am'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='freiwilliger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger', verbose_name='Freiwillige:r'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='pending',
            field=models.BooleanField(default=False, verbose_name='Wird bearbeitet'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='wiederholung',
            field=models.CharField(choices=[('T', 'Täglich'), ('W', 'Wöchentlich'), ('M', 'Monatlich'), ('J', 'Jährlich'), ('N', 'Nicht wiederholen')], default='N', max_length=1, verbose_name='Wiederholung'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='wiederholung_ende',
            field=models.DateField(blank=True, null=True, verbose_name='Wiederholung bis'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgabenprofil',
            name='aufgabenprofil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabenprofil', verbose_name='Aufgabenprofil'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgabenprofil',
            name='freiwilliger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger', verbose_name='Freiwillige:r'),
        ),
        migrations.AlterField(
            model_name='freiwilligerfotos',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='freiwilligerfotos',
            name='file',
            field=models.ImageField(upload_to='fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='freiwilligerfotos',
            name='freiwilliger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger', verbose_name='Freiwillige:r'),
        ),
        migrations.AlterField(
            model_name='freiwilligerfotos',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='freiwilligerupload',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='freiwilligerupload',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='freiwilligerupload',
            name='freiwilligeraufgabe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilligeraufgaben', verbose_name='Freiwillige:r Aufgabe'),
        ),
        migrations.AlterField(
            model_name='freiwilligerupload',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='jahrgang',
            name='ende',
            field=models.DateField(blank=True, null=True, verbose_name='Endedatum'),
        ),
        migrations.AlterField(
            model_name='jahrgang',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Jahrgang'),
        ),
        migrations.AlterField(
            model_name='jahrgang',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='jahrgang',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='kirchenzugehoerigkeit',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kirchenzugehoerigkeit-Name'),
        ),
        migrations.AlterField(
            model_name='kirchenzugehoerigkeit',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='freiwilliger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger', verbose_name='Freiwillige:r'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='post',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Posttitel'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.CreateModel(
            name='ProfilUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribut', models.CharField(max_length=50, verbose_name='Attribut')),
                ('value', models.TextField(verbose_name='Wert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Profil User',
                'verbose_name_plural': 'Profil User',
            },
        ),
    ]
