# Generated by Django 5.1.2 on 2025-01-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0008_alter_ampel_comment_alter_ampel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='faellig',
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='faellig_art',
            field=models.CharField(choices=[('V', 'Vor Einsatzstart'), ('W', 'Während Einsatz'), ('N', 'Nach Einsatzende'), ('A', 'Aktuelles Jahr')], default='W', max_length=1, verbose_name='Fällig Art'),
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='faellig_monat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fällig Monat'),
        ),
        migrations.AddField(
            model_name='aufgabe',
            name='faellig_tag',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fällig Tag'),
        ),
        migrations.AlterField(
            model_name='jahrgang',
            name='ende',
            field=models.DateField(verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='jahrgang',
            name='start',
            field=models.DateField(verbose_name='Startdatum'),
        ),
    ]
