# Generated by Django 5.1.2 on 2025-01-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0009_remove_aufgabe_faellig_aufgabe_faellig_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='faellig_monat',
            field=models.IntegerField(default=1, verbose_name='Fällig Monat'),
        ),
    ]
