# Generated by Django 5.1.2 on 2025-01-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0010_alter_aufgabe_faellig_monat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='faellig_monat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fällig Monat'),
        ),
    ]
