# Generated by Django 5.1.2 on 2025-01-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0011_alter_aufgabe_faellig_monat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabenprofil',
            name='aufgaben',
            field=models.ManyToManyField(blank=True, to='FW.aufgabe', verbose_name='Aufgaben'),
        ),
    ]
