# Generated by Django 5.1.2 on 2025-01-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0012_aufgabenprofil_aufgaben'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AufgabenprofilAufgabe',
        ),
    ]
