# Generated by Django 5.1.2 on 2025-01-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0013_delete_aufgabenprofilaufgabe'),
        ('ORG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgabenprofil',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation'),
            preserve_default=False,
        ),
    ]
