# Generated by Django 5.1.2 on 2025-01-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0014_freiwilligeraufgabenprofil_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freiwilligeraufgaben',
            options={'verbose_name': 'Freiwillige:r Aufgabe', 'verbose_name_plural': 'Freiwillige:r Aufgaben'},
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='einsatzland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.einsatzland', verbose_name='Einsatzland'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='einsatzstelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FW.einsatzstelle', verbose_name='Einsatzstelle'),
        ),
    ]
