# Generated by Django 5.1.2 on 2025-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0015_alter_freiwilligeraufgaben_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzland',
            name='code',
            field=models.CharField(default=1, max_length=2, verbose_name='Einsatzland-Code'),
            preserve_default=False,
        ),
    ]
