# Generated by Django 5.1.2 on 2025-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0016_einsatzland_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('T', 'Team'), ('F', 'Freiwillige:r')], default='F', max_length=1, verbose_name='Rolle'),
        ),
    ]
