# Generated by Django 5.1.2 on 2025-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0018_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profil_picture/', verbose_name='Profilbild'),
        ),
    ]
