# Generated by Django 5.1.2 on 2025-01-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0019_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabenprofil',
            options={'verbose_name': 'Aufgabenprofil', 'verbose_name_plural': 'Aufgabenprofil'},
        ),
        migrations.AlterModelOptions(
            name='freiwilligeraufgabenprofil',
            options={'verbose_name': 'Freiwilliger Aufgabenprofil', 'verbose_name_plural': 'Freiwilliger Aufgabenprofil'},
        ),
    ]
