# Generated by Django 5.1.2 on 2025-01-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0020_alter_aufgabenprofil_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='requires_submission',
            field=models.BooleanField(default=False, verbose_name='Bestätigung erforderlich'),
        ),
    ]
