# Generated by Django 5.1.2 on 2025-01-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0021_aufgabe_requires_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='requires_submission',
            field=models.BooleanField(default=True, verbose_name='Bestätigung erforderlich'),
        ),
    ]
