# Generated by Django 5.1.2 on 2025-01-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0022_alter_aufgabe_requires_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Datei'),
        ),
    ]
