# Generated by Django 5.1.2 on 2025-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0023_freiwilligeraufgaben_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Kommentar'),
        ),
    ]
