# Generated by Django 5.1.2 on 2025-01-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0024_freiwilligeraufgaben_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freiwilligeraufgaben',
            name='comment',
        ),
    ]
