# Generated by Django 5.1.2 on 2025-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0025_remove_freiwilligeraufgaben_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='last_reminder',
            field=models.DateField(blank=True, null=True, verbose_name='Letzte Erinnerung'),
        ),
    ]
