# Generated by Django 5.1.2 on 2025-01-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0026_freiwilligeraufgaben_last_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
