# Generated by Django 5.1.2 on 2025-01-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0027_delete_customuser'),
        ('ORG', '0005_alter_organisation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiluser',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgabenprofil',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation'),
        ),
    ]
