# Generated by Django 5.1.2 on 2025-01-30 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0028_profiluser_org_alter_freiwilligeraufgabenprofil_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatzstelle',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzland', verbose_name='Einsatzland'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='email',
            field=models.EmailField(default=1, max_length=100, verbose_name='E-Mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in'),
        ),
    ]
