# Generated by Django 5.1.2 on 2025-02-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0029_alter_einsatzstelle_land_alter_freiwilliger_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfallkontakt',
            name='freiwilliger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger', verbose_name='Freiwillige:r'),
        ),
    ]
