# Generated by Django 5.1.2 on 2025-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0030_alter_notfallkontakt_freiwilliger'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzland',
            name='apotheken',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Apotheken'),
        ),
        migrations.AddField(
            model_name='einsatzland',
            name='arztpraxen',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Arztpraxen'),
        ),
        migrations.AddField(
            model_name='einsatzland',
            name='informationen',
            field=models.TextField(blank=True, null=True, verbose_name='Weitere Informationen'),
        ),
        migrations.AddField(
            model_name='einsatzland',
            name='nummer_notdienst',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nummer Notdienst'),
        ),
        migrations.AddField(
            model_name='einsatzstelle',
            name='arbeitsvorgesetzter',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='einsatzstelle',
            name='partnerorganisation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partnerorganisation'),
        ),
    ]
