# Generated by Django 5.1.2 on 2025-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0031_einsatzland_apotheken_einsatzland_arztpraxen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzstelle',
            name='botschaft',
            field=models.TextField(blank=True, null=True, verbose_name='Botschaft'),
        ),
        migrations.AddField(
            model_name='einsatzstelle',
            name='informationen',
            field=models.TextField(blank=True, null=True, verbose_name='Weitere Informationen'),
        ),
        migrations.AddField(
            model_name='einsatzstelle',
            name='konsulat',
            field=models.TextField(blank=True, null=True, verbose_name='Konsulat'),
        ),
        migrations.AddField(
            model_name='einsatzstelle',
            name='mentor',
            field=models.TextField(blank=True, null=True, verbose_name='Mentor:in'),
        ),
        migrations.AlterField(
            model_name='einsatzstelle',
            name='arbeitsvorgesetzter',
            field=models.TextField(blank=True, null=True, verbose_name='Arbeitsvorgesetzte:r'),
        ),
        migrations.AlterField(
            model_name='einsatzstelle',
            name='partnerorganisation',
            field=models.TextField(blank=True, null=True, verbose_name='Partnerorganisation'),
        ),
    ]
