# Generated by Django 5.1.2 on 2025-02-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0032_einsatzstelle_botschaft_einsatzstelle_informationen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einsatzland',
            name='nummer_notdienst',
        ),
        migrations.AddField(
            model_name='einsatzland',
            name='notfallnummern',
            field=models.TextField(blank=True, null=True, verbose_name='Notfallnummern'),
        ),
        migrations.AlterField(
            model_name='einsatzland',
            name='apotheken',
            field=models.TextField(blank=True, null=True, verbose_name='Apotheken'),
        ),
        migrations.AlterField(
            model_name='einsatzland',
            name='arztpraxen',
            field=models.TextField(blank=True, null=True, verbose_name='Arztpraxen'),
        ),
    ]
