# Generated by Django 5.1.2 on 2025-02-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0033_remove_einsatzland_nummer_notdienst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notfallkontakt',
            name='phone',
        ),
        migrations.AddField(
            model_name='notfallkontakt',
            name='phone_mobil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon (Mobil)'),
        ),
        migrations.AddField(
            model_name='notfallkontakt',
            name='phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon (Arbeit)'),
        ),
    ]
