# Generated by Django 5.1.2 on 2025-02-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0034_remove_notfallkontakt_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notfallkontakt',
            old_name='phone_mobil',
            new_name='phone',
        ),
    ]
