# Generated by Django 5.1.2 on 2025-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0035_rename_phone_mobil_notfallkontakt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilliger',
            name='country',
            field=models.CharField(blank=True, default='Deutschland', max_length=100, null=True, verbose_name='Land'),
        ),
    ]
