# Generated by Django 5.1.2 on 2025-02-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0036_freiwilliger_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='currently_sending',
            field=models.BooleanField(default=False, verbose_name='Wird gerade gesendet'),
        ),
    ]
