# Generated by Django 5.1.2 on 2025-02-06 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0037_freiwilligeraufgaben_currently_sending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freiwilligeraufgaben',
            name='currently_sending',
        ),
    ]
