# Generated by Django 5.1.2 on 2025-02-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0038_remove_freiwilligeraufgaben_currently_sending'),
        ('ORG', '0014_jahrgangtyp_ordner_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='jahrgang',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.jahrgangtyp', verbose_name='Typ'),
        ),
    ]
