# Generated by Django 5.1.2 on 2025-02-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0039_jahrgang_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe',
            name='mitupload',
            field=models.BooleanField(default=True, verbose_name='Upload möglich'),
        ),
    ]
