# Generated by Django 5.1.2 on 2025-02-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0040_alter_aufgabe_mitupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='personalised_description',
            field=models.TextField(blank=True, null=True, verbose_name='Persönliche Beschreibung'),
        ),
    ]
