# Generated by Django 5.1.2 on 2025-02-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0041_freiwilligeraufgaben_personalised_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bildergallery',
            name='image',
            field=models.ImageField(upload_to='media/bilder/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/', verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='freiwilligerfotos',
            name='file',
            field=models.ImageField(upload_to='media/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='freiwilligerupload',
            name='file',
            field=models.FileField(upload_to='media/uploads/', verbose_name='Datei'),
        ),
    ]
