# Generated by Django 5.1.2 on 2025-03-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0044_historicalaufgabe_historicalbilder_and_more'),
        ('ORG', '0028_remove_historicalaufgabenteam_erledigt_von_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe',
            name='jahrgang_typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.jahrgangtyp', verbose_name='Jahrgang Typ'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe',
            name='jahrgang_typ',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.jahrgangtyp', verbose_name='Jahrgang Typ'),
        ),
    ]
