# Generated by Django 5.1.2 on 2025-03-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0045_aufgabe_jahrgang_typ_historicalaufgabe_jahrgang_typ'),
        ('ORG', '0028_remove_historicalaufgabenteam_erledigt_von_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freiwilligeraufgabenprofil',
            name='aufgabenprofil',
        ),
        migrations.RemoveField(
            model_name='freiwilligeraufgabenprofil',
            name='freiwilliger',
        ),
        migrations.RemoveField(
            model_name='freiwilligeraufgabenprofil',
            name='org',
        ),
        migrations.CreateModel(
            name='AufgabeZwischenschritte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabe', verbose_name='Aufgabe')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Aufgabe Zwischenschritt',
                'verbose_name_plural': 'Aufgabe Zwischenschritte',
            },
        ),
        migrations.CreateModel(
            name='FreiwilligerAufgabenZwischenschritte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabe_zwischenschritt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabezwischenschritte', verbose_name='Aufgabe Zwischenschritt')),
                ('freiwilliger_aufgabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilligeraufgaben', verbose_name='Freiwilliger Aufgabe')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Freiwilliger Aufgaben Zwischenschritt',
                'verbose_name_plural': 'Freiwilliger Aufgaben Zwischenschritte',
            },
        ),
        migrations.DeleteModel(
            name='Aufgabenprofil',
        ),
        migrations.DeleteModel(
            name='FreiwilligerAufgabenprofil',
        ),
    ]
