# Generated by Django 5.1.2 on 2025-03-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0046_remove_freiwilligeraufgabenprofil_aufgabenprofil_and_more'),
        ('ORG', '0028_remove_historicalaufgabenteam_erledigt_von_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfreiwilligerupload',
            name='freiwilligeraufgabe',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilligerupload',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilligerupload',
            name='org',
        ),
        migrations.AddField(
            model_name='freiwilligeraufgabenzwischenschritte',
            name='erledigt',
            field=models.BooleanField(default=False, verbose_name='Erledigt'),
        ),
        migrations.CreateModel(
            name='Aufgabenprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Aufgabenprofil-Name')),
                ('beschreibung', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('aufgaben', models.ManyToManyField(blank=True, to='FW.aufgabe', verbose_name='Aufgaben')),
                ('einsatzland', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzland', verbose_name='Einsatzland')),
                ('einsatzstelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FW.einsatzstelle', verbose_name='Einsatzstelle')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Aufgabenprofil',
                'verbose_name_plural': 'Aufgabenprofil',
            },
        ),
        migrations.CreateModel(
            name='FreiwilligerAufgabenprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aufgabenprofil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.aufgabenprofil', verbose_name='Aufgabenprofil')),
                ('freiwilliger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.freiwilliger', verbose_name='Freiwillige:r')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Freiwilliger Aufgabenprofil',
                'verbose_name_plural': 'Freiwilliger Aufgabenprofil',
            },
        ),
        migrations.DeleteModel(
            name='FreiwilligerUpload',
        ),
        migrations.DeleteModel(
            name='HistoricalFreiwilligerUpload',
        ),
    ]
