# Generated by Django 5.1.2 on 2025-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0047_remove_historicalfreiwilligerupload_freiwilligeraufgabe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='erledigte_zwischenschritte',
            field=models.ManyToManyField(blank=True, to='FW.aufgabezwischenschritte', verbose_name='Erledigte Zwischenschritte'),
        ),
    ]
