# Generated by Django 5.1.2 on 2025-03-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0048_freiwilligeraufgaben_erledigte_zwischenschritte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freiwilligeraufgaben',
            name='erledigte_zwischenschritte',
        ),
    ]
