# Generated by Django 5.1.2 on 2025-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0049_remove_freiwilligeraufgaben_erledigte_zwischenschritte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabezwischenschritte',
            name='beschreibung',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Beschreibung'),
        ),
    ]
