# Generated by Django 5.1.2 on 2025-03-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0051_aufgabe_benachrichtigung_cc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aufgabe',
            name='benachrichtigung_cc',
        ),
        migrations.RemoveField(
            model_name='historicalaufgabe',
            name='benachrichtigung_cc',
        ),
        migrations.AddField(
            model_name='freiwilligeraufgaben',
            name='benachrichtigung_cc',
            field=models.CharField(blank=True, help_text='Komma-getrennte E-Mail-Adressen', max_length=255, null=True, verbose_name='CC an Mailadressen'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilligeraufgaben',
            name='benachrichtigung_cc',
            field=models.CharField(blank=True, help_text='Komma-getrennte E-Mail-Adressen', max_length=255, null=True, verbose_name='CC an Mailadressen'),
        ),
    ]
