# Generated by Django 5.1.2 on 2025-03-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0052_remove_aufgabe_benachrichtigung_cc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freiwilligeraufgaben',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/', verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='historicalfreiwilligeraufgaben',
            name='file',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Datei'),
        ),
    ]
