# Generated by Django 5.1.2 on 2025-03-24 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0053_alter_freiwilligeraufgaben_file_and_more'),
        ('ORG', '0032_remove_referentenaufgaben_aufgabe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freiwilliger',
            name='country',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='geburtsdatum',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='geschlecht',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='phone_einsatzland',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='freiwilliger',
            name='strasse',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='geburtsdatum',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='geschlecht',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='phone_einsatzland',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='plz',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger',
            name='strasse',
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Attribut')),
                ('type', models.CharField(choices=[('T', 'Text'), ('L', 'Langer Text'), ('N', 'Zahl'), ('D', 'Datum'), ('B', 'Wahrheitswert'), ('E', 'E-Mail'), ('P', 'Telefon'), ('F', 'Datei')], max_length=1, verbose_name='Feldtyp')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Attribut',
                'verbose_name_plural': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='FreiwlligerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Wert')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FW.attribute', verbose_name='Attribut')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
            ],
            options={
                'verbose_name': 'Freiwilliger Attribut',
                'verbose_name_plural': 'Freiwilliger Attribute',
            },
        ),
    ]
