# Generated by Django 5.1.2 on 2025-03-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0054_remove_freiwilliger_country_and_more'),
        ('ORG', '0032_remove_referentenaufgaben_aufgabe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='jahrgang_typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.jahrgangtyp', verbose_name='Jahrgang Typ'),
        ),
    ]
