# Generated by Django 5.1.2 on 2025-04-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0055_attribute_jahrgang_typ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freiwlligerattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='freiwlligerattribute',
            name='org',
        ),
        migrations.RemoveField(
            model_name='freiwlligerattribute',
            name='user',
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='country',
            field=models.CharField(blank=True, default='Deutschland', max_length=100, null=True, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers'), ('N', 'Keine Angabe')], max_length=1, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='ort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='phone_einsatzland',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Einsatzland'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='strasse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='country',
            field=models.CharField(blank=True, default='Deutschland', max_length=100, null=True, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('M', 'Männlich'), ('W', 'Weiblich'), ('D', 'Divers'), ('N', 'Keine Angabe')], max_length=1, null=True, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='Nachname'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='ort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='phone_einsatzland',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Einsatzland'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='strasse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straße'),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='FreiwlligerAttribute',
        ),
    ]
