# Generated by Django 5.1.2 on 2025-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0056_remove_freiwlligerattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freiwilliger',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='freiwilliger',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='historicalfreiwilliger',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='historicalfreiwilliger',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='historicalfreiwilliger',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Nachname'),
        ),
    ]
