# Generated by Django 5.1.2 on 2025-04-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0058_alter_freiwilliger_email_and_more'),
        ('Global', '0025_remove_historicalfreiwilliger2_einsatzland_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freiwilliger',
            name='einsatzland2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.einsatzland2', verbose_name='Einsatzland'),
        ),
        migrations.AddField(
            model_name='freiwilliger',
            name='einsatzstelle2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.einsatzstelle2', verbose_name='Einsatzstelle'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='einsatzland2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.einsatzland2', verbose_name='Einsatzland'),
        ),
        migrations.AddField(
            model_name='historicalfreiwilliger',
            name='einsatzstelle2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.einsatzstelle2', verbose_name='Einsatzstelle'),
        ),
    ]
