# Generated by Django 5.1.2 on 2025-04-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0060_remove_aufgabe_jahrgang_typ_remove_aufgabe_org_and_more'),
        ('ORG', '0033_remove_ordner_color_remove_historicalordner_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Einsatzland',
        ),
        migrations.DeleteModel(
            name='Einsatzstelle',
        ),
        migrations.DeleteModel(
            name='Entsendeform',
        ),
        migrations.DeleteModel(
            name='FreiwilligerAufgaben',
        ),
        migrations.DeleteModel(
            name='FreiwilligerAufgabenprofil',
        ),
        migrations.DeleteModel(
            name='FreiwilligerAufgabenZwischenschritte',
        ),
        migrations.DeleteModel(
            name='FreiwilligerFotos',
        ),
        migrations.DeleteModel(
            name='HistoricalAufgabe',
        ),
        migrations.DeleteModel(
            name='HistoricalBilder',
        ),
        migrations.DeleteModel(
            name='HistoricalBilderGallery',
        ),
        migrations.DeleteModel(
            name='HistoricalEinsatzland',
        ),
        migrations.DeleteModel(
            name='HistoricalEinsatzstelle',
        ),
        migrations.DeleteModel(
            name='HistoricalEntsendeform',
        ),
        migrations.DeleteModel(
            name='HistoricalFreiwilligerAufgaben',
        ),
        migrations.DeleteModel(
            name='HistoricalFreiwilligerFotos',
        ),
        migrations.DeleteModel(
            name='HistoricalJahrgang',
        ),
        migrations.DeleteModel(
            name='HistoricalKirchenzugehoerigkeit',
        ),
        migrations.DeleteModel(
            name='HistoricalPost',
        ),
        migrations.DeleteModel(
            name='HistoricalProfilUser',
        ),
        migrations.DeleteModel(
            name='Jahrgang',
        ),
        migrations.DeleteModel(
            name='Kirchenzugehoerigkeit',
        ),
        migrations.DeleteModel(
            name='Notfallkontakt',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='ProfilUser',
        ),
    ]
