# Generated by Django 5.1.2 on 2025-01-26 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('T', 'Team'), ('F', 'Freiwillige:r')], default='F', max_length=1, verbose_name='Rolle')),
                ('profil_picture', models.ImageField(blank=True, null=True, upload_to='profil_picture/', verbose_name='Profilbild')),
                ('einmalpasswort', models.CharField(blank=True, max_length=20, null=True, verbose_name='Einmalpasswort')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
