# Generated by Django 5.1.2 on 2025-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('F', 'Freiwillige:r'), ('R', 'Referent:in'), ('E', 'Ehemalige:r'), ('T', 'Team')], default='F', max_length=1, verbose_name='Rolle'),
        ),
    ]
