# Generated by Django 5.2.2 on 2025-09-06 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0002_aufgabe2_attachment_historicalaufgabe2_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='already_sent_to',
            field=models.ManyToManyField(blank=True, help_text='Benutzer, die diesen Post bereits erhalten haben', related_name='already_sent_to', to=settings.AUTH_USER_MODEL, verbose_name='Bereits gesendet an'),
        ),
    ]
