# Generated by Django 5.2.6 on 2025-09-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0003_post2_already_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe2',
            name='with_email_notification',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, wird eine E-Mail-Benachrichtigung an die Organisation gesendet, wenn die Aufgabe erledigt ist', verbose_name='E-Mail-Benachrichtigung'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe2',
            name='with_email_notification',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, wird eine E-Mail-Benachrichtigung an die Organisation gesendet, wenn die Aufgabe erledigt ist', verbose_name='E-Mail-Benachrichtigung'),
        ),
        migrations.AlterField(
            model_name='bilder2',
            name='titel',
            field=models.CharField(max_length=100, verbose_name='Bildtitel'),
        ),
        migrations.AlterField(
            model_name='historicalbilder2',
            name='titel',
            field=models.CharField(max_length=100, verbose_name='Bildtitel'),
        ),
    ]
