# Generated by Django 5.1.2 on 2025-02-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonym'),
        ),
    ]
