# Generated by Django 5.2.6 on 2025-09-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0004_aufgabe2_with_email_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkalenderevent',
            name='location',
            field=models.CharField(blank=True, help_text='Ort des Termins (optional)', max_length=255, null=True, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='kalenderevent',
            name='location',
            field=models.CharField(blank=True, help_text='Ort des Termins (optional)', max_length=255, null=True, verbose_name='Ort'),
        ),
    ]
