# Generated by Django 5.2.7 on 2025-10-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0005_historicalkalenderevent_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampel2',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
