# Generated by Django 5.2.7 on 2025-10-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0006_ampel2_submission_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilder2',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbilder2',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
