# Generated by Django 5.1.2 on 2025-02-07 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0006_kalenderevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalenderevent',
            name='user',
        ),
        migrations.AddField(
            model_name='kalenderevent',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in'),
        ),
    ]
