# Generated by Django 5.1.2 on 2025-02-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0007_remove_kalenderevent_user_kalenderevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profil_picture/', verbose_name='Profilbild'),
        ),
    ]
