# Generated by Django 5.2.7 on 2025-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0007_bilder2_submission_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='ampel',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Ampelmeldungen für diese Gruppe abgeben zu können', verbose_name='Ampelmeldungen abgeben'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='bilder',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Bilder für diese Gruppe hochladen zu können', verbose_name='Bilder hochladen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='notfallkontakt',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Notfallkontakte für diese Gruppe anlegen zu können', verbose_name='Notfallkontakt anlegen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='posts',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Posts für diese Gruppe verfassen zu können', verbose_name='Posts verfassen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='ampel',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Ampelmeldungen für diese Gruppe abgeben zu können', verbose_name='Ampelmeldungen abgeben'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='bilder',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Bilder für diese Gruppe hochladen zu können', verbose_name='Bilder hochladen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='notfallkontakt',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Notfallkontakte für diese Gruppe anlegen zu können', verbose_name='Notfallkontakt anlegen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='posts',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Posts für diese Gruppe verfassen zu können', verbose_name='Posts verfassen'),
        ),
    ]
