# Generated by Django 5.1.2 on 2025-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0008_alter_customuser_profil_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profil_picture/', verbose_name='Profilbild'),
        ),
    ]
