# Generated by Django 5.2.7 on 2025-10-08 14:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0008_alter_historicalpersoncluster_ampel_and_more'),
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('einsatzland', 'Einsatzland'), ('einsatzstelle', 'Einsatzstelle')], max_length=20, verbose_name='Änderungstyp')),
                ('object_id', models.PositiveIntegerField(verbose_name='Objekt-ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20, verbose_name='Status')),
                ('field_changes', models.JSONField(help_text='Gespeicherte Feldänderungen als JSON', verbose_name='Feldänderungen')),
                ('reason', models.TextField(blank=True, help_text='Begründung für die Änderung', verbose_name='Begründung')),
                ('review_comment', models.TextField(blank=True, help_text='Kommentar des Prüfers', verbose_name='Prüfungskommentar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprüft am')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Angefragt von')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Geprüft von')),
            ],
            options={
                'verbose_name': 'Änderungsantrag',
                'verbose_name_plural': 'Änderungsanträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalChangeRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('einsatzland', 'Einsatzland'), ('einsatzstelle', 'Einsatzstelle')], max_length=20, verbose_name='Änderungstyp')),
                ('object_id', models.PositiveIntegerField(verbose_name='Objekt-ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20, verbose_name='Status')),
                ('field_changes', models.JSONField(help_text='Gespeicherte Feldänderungen als JSON', verbose_name='Feldänderungen')),
                ('reason', models.TextField(blank=True, help_text='Begründung für die Änderung', verbose_name='Begründung')),
                ('review_comment', models.TextField(blank=True, help_text='Kommentar des Prüfers', verbose_name='Prüfungskommentar')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Erstellt am')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprüft am')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation', verbose_name='Organisation')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Angefragt von')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Geprüft von')),
            ],
            options={
                'verbose_name': 'historical Änderungsantrag',
                'verbose_name_plural': 'historical Änderungsanträge',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
