# Generated by Django 5.2.7 on 2025-10-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0009_changerequest_historicalchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einsatzstelle2',
            name='max_freiwillige',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Maximale Anzahl Freiwillige'),
        ),
        migrations.AlterField(
            model_name='historicaleinsatzstelle2',
            name='max_freiwillige',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Maximale Anzahl Freiwillige'),
        ),
    ]
