# Generated by Django 5.2.7 on 2025-10-20 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BW', '0005_alter_bewerber_options'),
        ('Global', '0010_alter_einsatzstelle2_max_freiwillige_and_more'),
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BewerberKommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstellt am')),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BW.bewerber', verbose_name='Bewerber:in')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Bewerber Kommentar',
                'verbose_name_plural': 'Bewerber Kommentare',
                'ordering': ['-date_created'],
            },
        ),
    ]
