# Generated by Django 5.1.2 on 2025-02-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0010_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
