# Generated by Django 5.2.7 on 2025-10-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0011_bewerberkommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampel2',
            name='read',
            field=models.BooleanField(default=False, help_text='Zeigt an, ob die Ampel als gelesen markiert ist', verbose_name='Gelesen'),
        ),
    ]
