# Generated by Django 5.2.7 on 2025-10-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0012_ampel2_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='visible_in_profile',
            field=models.BooleanField(default=True, help_text='Aktivieren, um das Feld im Profil auch für die Freiwillige sichtbar zu machen', verbose_name='Im Profil anzeigen'),
        ),
    ]
