# Generated by Django 5.1.2 on 2025-02-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0012_historicalcustomuser_historicalkalenderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'History Record',
                'verbose_name_plural': 'History Records',
                'db_table': 'global_history',
                'managed': False,
            },
        ),
    ]
