# Generated by Django 5.2.8 on 2025-11-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0013_attribute_visible_in_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe2',
            name='visible_by_team',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Aufgabe auch für Teammitglieder mit gleichem Land sichtbar zu machen', verbose_name='Für Team sichtbar'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe2',
            name='visible_by_team',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Aufgabe auch für Teammitglieder mit gleichem Land sichtbar zu machen', verbose_name='Für Team sichtbar'),
        ),
    ]
