# Generated by Django 5.1.2 on 2025-02-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0013_globalhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalHistory',
        ),
    ]
