# Generated by Django 5.2.8 on 2025-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0014_aufgabe2_visible_by_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe2',
            name='visible_by_team',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Aufgabe auch für Teammitglieder mit gleichem Land sichtbar zu machen (nur für Aufgaben für Freiwillige)', verbose_name='Für Team sichtbar'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='visible_by_team',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Aufgabe auch für Teammitglieder mit gleichem Land sichtbar zu machen (nur für Aufgaben für Freiwillige)', verbose_name='Für Team sichtbar'),
        ),
    ]
