# Generated by Django 5.1.2 on 2025-03-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0014_delete_globalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='einmalpasswort',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=20, null=True, verbose_name='Einmalpasswort'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='einmalpasswort',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=20, null=True, verbose_name='Einmalpasswort'),
        ),
    ]
