# Generated by Django 5.1.2 on 2025-03-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0015_alter_customuser_einmalpasswort_and_more'),
        ('ORG', '0030_alter_dokument_dokument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('aufgaben', models.BooleanField(default=False, verbose_name='Aufgaben')),
                ('ampel', models.BooleanField(default=False, verbose_name='Ampel')),
                ('dokumente', models.BooleanField(default=False, verbose_name='Dokumente')),
                ('kalender', models.BooleanField(default=False, verbose_name='Kalender')),
                ('role', models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('F', 'Freiwillige:r'), ('R', 'Referent:in'), ('E', 'Ehemalige:r'), ('T', 'Team')], default='F', max_length=1, verbose_name='Rolle')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Benutzercluster',
                'verbose_name_plural': 'Benutzercluster',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.usercluster', verbose_name='Benutzercluster'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='user_cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.usercluster', verbose_name='Benutzercluster'),
        ),
    ]
