# Generated by Django 5.2.8 on 2025-11-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0015_alter_aufgabe2_visible_by_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost2',
            name='text',
            field=models.TextField(blank=True, help_text='Text des Posts', null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='text',
            field=models.TextField(blank=True, help_text='Text des Posts', null=True, verbose_name='Text'),
        ),
    ]
