# Generated by Django 5.2.8 on 2025-11-19 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0016_alter_historicalpost2_text_alter_post2_text'),
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersoncluster',
            name='map',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Standortkarte für diese Gruppe sichtbar zu machen', verbose_name='Karte sichtbar'),
        ),
        migrations.AddField(
            model_name='personcluster',
            name='map',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Standortkarte für diese Gruppe sichtbar zu machen', verbose_name='Karte sichtbar'),
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Erstellt am')),
                ('zip_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Karte',
                'verbose_name_plural': 'Karten',
                'ordering': ['-date_created'],
            },
        ),
    ]
