# Generated by Django 5.1.2 on 2025-03-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0016_usercluster_customuser_user_cluster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_cluster',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='user_cluster',
        ),
        migrations.DeleteModel(
            name='UserCluster',
        ),
    ]
