# Generated by Django 5.1.2 on 2025-03-24 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0017_remove_customuser_user_cluster_and_more'),
        ('ORG', '0032_remove_referentenaufgaben_aufgabe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jahrgang_typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.jahrgangtyp', verbose_name='Jahrgangstyp'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='jahrgang_typ',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.jahrgangtyp', verbose_name='Jahrgangstyp'),
        ),
    ]
