# Generated by Django 5.2.8 on 2025-11-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0017_historicalpersoncluster_map_personcluster_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplocation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ'),
        ),
    ]
