# Generated by Django 5.1.2 on 2025-04-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0018_customuser_jahrgang_typ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jahrgang_typ',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='jahrgang_typ',
        ),
    ]
