# Generated by Django 5.2.8 on 2025-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0018_alter_maplocation_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identifier',
            field=models.CharField(blank=True, help_text='Identifikator für den Benutzer', max_length=255, null=True, unique=True, verbose_name='Identifikator'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, help_text='Identifikator für den Benutzer', max_length=255, null=True, verbose_name='Identifikator'),
        ),
    ]
