# Generated by Django 5.2.8 on 2025-11-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0019_customuser_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost2',
            name='image',
            field=models.TextField(blank=True, help_text='Bild des Posts', max_length=100, null=True, verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='post2',
            name='image',
            field=models.ImageField(blank=True, help_text='Bild des Posts', null=True, upload_to='posts/', verbose_name='Bild'),
        ),
    ]
