# Generated by Django 5.2.8 on 2025-11-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0020_historicalpost2_image_post2_image'),
        ('ORG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Text der Antwort', null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, help_text='Bild der Antwort', null=True, upload_to='posts/', verbose_name='Bild')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('original_post', models.ForeignKey(help_text='Originaler Post, auf den dieser Post antwortet', on_delete=django.db.models.deletion.CASCADE, to='Global.post2', verbose_name='Originaler Post')),
                ('user', models.ForeignKey(help_text='Benutzer, der die Antwort erstellt hat', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Post Antwort',
                'verbose_name_plural': 'Post Antworten',
            },
        ),
    ]
