# Generated by Django 5.1.2 on 2025-04-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0020_dokumentcolor2_organisation2_remove_customuser_role_and_more'),
        ('ORG', '0032_remove_referentenaufgaben_aufgabe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganisation2',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='jahrgang2',
            name='org',
        ),
        migrations.RemoveField(
            model_name='jahrgang2',
            name='typ',
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='org',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation'),
        ),
        migrations.AlterField(
            model_name='dokument2',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('L', 'Langer Text'), ('N', 'Zahl'), ('D', 'Datum'), ('B', 'Wahrheitswert'), ('E', 'E-Mail'), ('P', 'Telefon'), ('C', 'Auswahl')], default='T', max_length=1, verbose_name='Feldtyp'),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Wert'),
        ),
        migrations.DeleteModel(
            name='HistoricalJahrgang2',
        ),
        migrations.DeleteModel(
            name='HistoricalOrganisation2',
        ),
        migrations.DeleteModel(
            name='Jahrgang2',
        ),
        migrations.DeleteModel(
            name='Organisation2',
        ),
    ]
