# Generated by Django 5.1.2 on 2025-04-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0021_remove_historicalorganisation2_history_user_and_more'),
        ('ORG', '0032_remove_referentenaufgaben_aufgabe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_start_time', models.DateTimeField(verbose_name='Wartung startet am')),
                ('maintenance_end_time', models.DateTimeField(verbose_name='Wartung endet am')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Wartung',
                'verbose_name_plural': 'Wartungen',
            },
        ),
    ]
