# Generated by Django 5.2.8 on 2025-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0021_postresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument2',
            name='identifier',
            field=models.CharField(blank=True, help_text='Eindeutige Kennung der Datei', max_length=64, null=True, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='historicaldokument2',
            name='identifier',
            field=models.CharField(blank=True, help_text='Eindeutige Kennung der Datei', max_length=64, null=True, verbose_name='Identifier'),
        ),
    ]
