# Generated by Django 5.2.8 on 2025-12-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0022_dokument2_identifier_historicaldokument2_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument2',
            name='identifier',
            field=models.CharField(blank=True, help_text='Eindeutige Kennung der Datei', max_length=255, null=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='identifier',
            field=models.CharField(blank=True, help_text='Eindeutige Kennung der Datei', max_length=255, null=True, verbose_name='Identifier'),
        ),
    ]
