# Generated by Django 5.1.2 on 2025-04-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0022_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='org',
        ),
    ]
