# Generated by Django 6.0.1 on 2026-02-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0023_alter_dokument2_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcluster',
            options={'ordering': ['view'], 'verbose_name': 'Benutzergruppe', 'verbose_name_plural': 'Benutzergruppen'},
        ),
        migrations.AddField(
            model_name='einsatzstelle2',
            name='ende_geplant',
            field=models.CharField(blank=True, help_text='Das Datum wann das Einsatzende geplant ist (Format: DD.MM. (z.B. 15.03.))', max_length=6, null=True, verbose_name='Ende geplant'),
        ),
        migrations.AddField(
            model_name='einsatzstelle2',
            name='start_geplant',
            field=models.CharField(blank=True, help_text='Das Datum wann der Einsatzstart geplant ist (Format: DD.MM. (z.B. 15.03.))', max_length=6, null=True, verbose_name='Start geplant'),
        ),
        migrations.AddField(
            model_name='historicaleinsatzstelle2',
            name='ende_geplant',
            field=models.CharField(blank=True, help_text='Das Datum wann das Einsatzende geplant ist (Format: DD.MM. (z.B. 15.03.))', max_length=6, null=True, verbose_name='Ende geplant'),
        ),
        migrations.AddField(
            model_name='historicaleinsatzstelle2',
            name='start_geplant',
            field=models.CharField(blank=True, help_text='Das Datum wann der Einsatzstart geplant ist (Format: DD.MM. (z.B. 15.03.))', max_length=6, null=True, verbose_name='Start geplant'),
        ),
    ]
