# Generated by Django 5.1.2 on 2025-04-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0023_remove_maintenance_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenten2',
            name='land',
        ),
        migrations.RemoveField(
            model_name='referenten2',
            name='org',
        ),
        migrations.RemoveField(
            model_name='referenten2',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalReferenten2',
        ),
        migrations.DeleteModel(
            name='Referenten2',
        ),
    ]
