# Generated by Django 5.1.2 on 2025-04-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0024_remove_referenten2_land_remove_referenten2_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfreiwilliger2',
            name='einsatzland',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger2',
            name='einsatzstelle',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger2',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger2',
            name='org',
        ),
        migrations.RemoveField(
            model_name='historicalfreiwilliger2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Freiwilliger2',
        ),
        migrations.DeleteModel(
            name='HistoricalFreiwilliger2',
        ),
    ]
