# Generated by Django 6.0.1 on 2026-02-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0024_alter_personcluster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersoncluster',
            name='active',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert, können sich Benutzer in dieser Gruppe nicht mehr anmelden und die Benutzergruppe wird nicht mehr angezeigt', verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='personcluster',
            name='active',
            field=models.BooleanField(default=True, help_text='Wenn deaktiviert, können sich Benutzer in dieser Gruppe nicht mehr anmelden und die Benutzergruppe wird nicht mehr angezeigt', verbose_name='Aktiv'),
        ),
    ]
