# Generated by Django 6.0.3 on 2026-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0025_historicalpersoncluster_active_personcluster_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='visibility',
            field=models.CharField(choices=[('P', 'Für alle sichtbar'), ('F', 'Nur für andere Freiwillige/Ehemalige in meinem Jahrgang'), ('O', 'Nur für Organisation')], default='F', max_length=1, verbose_name='Sichtbarkeit'),
        ),
    ]
