# Generated by Django 5.1.2 on 2025-04-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0025_remove_historicalfreiwilliger2_einsatzland_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalordner2',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='ordner2',
            name='typ',
        ),
        migrations.AddField(
            model_name='ordner2',
            name='typ',
            field=models.ManyToManyField(to='Global.personcluster', verbose_name='Typ'),
        ),
    ]
