# Generated by Django 6.0.3 on 2026-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0026_maplocation_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='einmalpasswort_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Einmalpasswort abläuft am'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='einmalpasswort_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Einmalpasswort abläuft am'),
        ),
    ]
