# Generated by Django 5.1.2 on 2025-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0026_remove_historicalordner2_typ_remove_ordner2_typ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabencluster',
            name='faellig_art',
            field=models.CharField(blank=True, choices=[('V', 'Vor Einsatz'), ('W', 'Während Einsatz'), ('N', 'Nach Einsatz')], help_text='Nur für Freiwillige', max_length=1, null=True, verbose_name='Fällig Art'),
        ),
    ]
