# Generated by Django 6.0.4 on 2026-04-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0027_customuser_einmalpasswort_expires_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Eigenes Feld', 'verbose_name_plural': 'Eigene Felder'},
        ),
        migrations.AlterModelOptions(
            name='userattribute',
            options={'verbose_name': 'Eigenes Feld Benutzer:in', 'verbose_name_plural': 'Eigene Felder Benutzer:innen'},
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Global.attribute', verbose_name='Eigenes Feld'),
        ),
    ]
