# Generated by Django 5.1.2 on 2025-04-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0027_aufgabencluster_faellig_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aufgabencluster',
            old_name='faellig_art',
            new_name='type',
        ),
    ]
