# Generated by Django 5.1.2 on 2025-04-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0028_rename_faellig_art_aufgabencluster_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluseraufgaben',
            name='wiederholung',
        ),
        migrations.RemoveField(
            model_name='historicaluseraufgaben',
            name='wiederholung_ende',
        ),
        migrations.RemoveField(
            model_name='useraufgaben',
            name='wiederholung',
        ),
        migrations.RemoveField(
            model_name='useraufgaben',
            name='wiederholung_ende',
        ),
        migrations.AddField(
            model_name='aufgabe2',
            name='wiederholung',
            field=models.BooleanField(default=False, verbose_name='Wiederholung'),
        ),
        migrations.AddField(
            model_name='aufgabe2',
            name='wiederholung_ende',
            field=models.DateField(blank=True, null=True, verbose_name='Wiederholung bis'),
        ),
        migrations.AddField(
            model_name='aufgabe2',
            name='wiederholung_interval_wochen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wiederholung Intervall in Wochen'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe2',
            name='wiederholung',
            field=models.BooleanField(default=False, verbose_name='Wiederholung'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe2',
            name='wiederholung_ende',
            field=models.DateField(blank=True, null=True, verbose_name='Wiederholung bis'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe2',
            name='wiederholung_interval_wochen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wiederholung Intervall in Wochen'),
        ),
    ]
