# Generated by Django 6.0.4 on 2026-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0028_alter_attribute_options_alter_userattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ampel2',
            options={'verbose_name': 'Ampelmeldung', 'verbose_name_plural': 'Ampelmeldungen'},
        ),
        migrations.AddField(
            model_name='historicalpersoncluster',
            name='own_signin_token',
            field=models.CharField(blank=True, help_text='Wenn leer, kann sich kein Benutzer in dieser Gruppe selbst registrieren', max_length=255, null=True, verbose_name='Anmeldetoken zum eigenen Registrieren'),
        ),
        migrations.AddField(
            model_name='personcluster',
            name='own_signin_token',
            field=models.CharField(blank=True, help_text='Wenn leer, kann sich kein Benutzer in dieser Gruppe selbst registrieren', max_length=255, null=True, verbose_name='Anmeldetoken zum eigenen Registrieren'),
        ),
    ]
