# Generated by Django 6.0.6 on 2026-07-23 09:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0029_alter_ampel2_options_and_more'),
        ('ORG', '0003_historicalorganisation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_ampel_reminder',
            field=models.DateField(blank=True, help_text='Datum der letzten versendeten Ampel-Erinnerung', null=True, verbose_name='Letzte Ampel-Erinnerung'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='last_ampel_reminder',
            field=models.DateField(blank=True, help_text='Datum der letzten versendeten Ampel-Erinnerung', null=True, verbose_name='Letzte Ampel-Erinnerung'),
        ),
        migrations.AlterField(
            model_name='ampel2',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am'),
        ),
        migrations.CreateModel(
            name='AmpelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Wenn aktiviert, werden Ampel-Erinnerungen im konfigurierten Zeitraum gesendet.', verbose_name='Erinnerungen aktiv')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'Englisch')], default='de', help_text='Sprache der Erinnerungs-E-Mail (nur diese Sprache wird angezeigt).', max_length=2, verbose_name='Sprache')),
                ('reminder_interval_days', models.IntegerField(default=7, help_text='Anzahl der Tage zwischen Ampel-Erinnerungen. 0 = Erinnerungen deaktiviert.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erinnerungsintervall (Tage)')),
                ('reminder_start_date', models.DateField(blank=True, help_text='Ab diesem Datum werden Erinnerungen gesendet. Leer = erste Ampelmeldung der Gruppe.', null=True, verbose_name='Erinnerungen ab')),
                ('reminder_end_date', models.DateField(blank=True, help_text='Bis zu diesem Datum werden Erinnerungen gesendet. Leer = Start + 1 Jahr.', null=True, verbose_name='Erinnerungen bis')),
                ('message_text', models.TextField(default='Bitte gib zeitnah deine Ampelmeldung ab. So wissen wir, wie es dir geht und können dich bei Bedarf unterstützen.', help_text='Text für E-Mail- und Push-Erinnerungen an Ampelmeldungen', verbose_name='Nachrichtentext')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('person_cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ampel_configuration', to='Global.personcluster', verbose_name='Benutzergruppe')),
            ],
            options={
                'verbose_name': 'Ampel-Konfiguration',
                'verbose_name_plural': 'Ampel-Konfigurationen',
            },
        ),
    ]
