# Generated by Django 5.1.2 on 2025-04-11 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0029_remove_historicaluseraufgaben_wiederholung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_monat',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Fällig Monat'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_tag',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Fällig Tag'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_tage_nach_start',
            field=models.IntegerField(blank=True, help_text='Nur für Freiwillige', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fällig Tage nach Einsatzstart'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_tage_vor_ende',
            field=models.IntegerField(blank=True, help_text='Nur für Freiwillige', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fällig Tage vor Einsatzende'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='wiederholung_interval_wochen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wiederholung Intervall in Wochen'),
        ),
        migrations.AlterField(
            model_name='aufgabencluster',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Aufgaben Filter'),
        ),
        migrations.RemoveField(
            model_name='aufgabencluster',
            name='person_cluster',
        ),
        migrations.AlterField(
            model_name='aufgabencluster',
            name='type',
            field=models.CharField(blank=True, choices=[('V', 'Vor Einsatz'), ('W', 'Während Einsatz'), ('N', 'Nach Einsatz')], help_text='Nur für Freiwillige', max_length=1, null=True, verbose_name='Fällig Zeitraum'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_monat',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Fällig Monat'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_tag',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Fällig Tag'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_tage_nach_start',
            field=models.IntegerField(blank=True, help_text='Nur für Freiwillige', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fällig Tage nach Einsatzstart'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_tage_vor_ende',
            field=models.IntegerField(blank=True, help_text='Nur für Freiwillige', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Fällig Tage vor Einsatzende'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='wiederholung_interval_wochen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wiederholung Intervall in Wochen'),
        ),
        migrations.AddField(
            model_name='aufgabencluster',
            name='person_cluster',
            field=models.ManyToManyField(to='Global.personcluster', verbose_name='Person Cluster'),
        ),
    ]
