# Generated by Django 6.0.6 on 2026-07-23 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0030_customuser_last_ampel_reminder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ampelconfiguration',
            options={'verbose_name': 'Ampel-Erinnerung', 'verbose_name_plural': 'Ampel-Erinnerungen'},
        ),
        migrations.AlterField(
            model_name='ampelconfiguration',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, werden Ampel-Erinnerungen im konfigurierten Zeitraum gesendet.', verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='ampelconfiguration',
            name='reminder_interval_days',
            field=models.IntegerField(default=14, help_text='Anzahl der Tage zwischen Ampel-Erinnerungen. 0 = Erinnerungen deaktiviert.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Intervall (Tage)'),
        ),
    ]
