# Generated by Django 5.1.2 on 2025-04-11 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0030_alter_aufgabe2_faellig_monat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Benutzerdatenfeld', 'verbose_name_plural': 'Benutzerdatenfelder'},
        ),
        migrations.AlterModelOptions(
            name='aufgabencluster',
            options={'verbose_name': 'Aufgabenkategorie', 'verbose_name_plural': 'Aufgabenkategorien'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersoncluster',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Benutzergruppe', 'verbose_name_plural': 'historical Benutzergruppen'},
        ),
        migrations.AlterModelOptions(
            name='historicaluseraufgaben',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Benutzeraufgabe', 'verbose_name_plural': 'historical Benutzeraufgaben'},
        ),
        migrations.AlterModelOptions(
            name='personcluster',
            options={'verbose_name': 'Benutzergruppe', 'verbose_name_plural': 'Benutzergruppen'},
        ),
        migrations.AlterModelOptions(
            name='useraufgaben',
            options={'verbose_name': 'Benutzeraufgabe', 'verbose_name_plural': 'Benutzeraufgaben'},
        ),
        migrations.AlterField(
            model_name='ampel2',
            name='comment',
            field=models.TextField(blank=True, help_text='Kommentar zur Erläuterung des Status', null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='ampel2',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='ampel2',
            name='status',
            field=models.CharField(choices=[('G', 'Grün'), ('Y', 'Gelb'), ('R', 'Rot')], help_text='Aktueller Status (Grün = alles in Ordnung, Gelb = Aufmerksamkeit nötig, Rot = unmittelbare Hilfe erforderlich)', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ampel2',
            name='user',
            field=models.ForeignKey(help_text='Benutzer:in, für den dieser Status gilt', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(help_text='Name des benutzerdefinierten Datenfelds', max_length=50, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='person_cluster',
            field=models.ManyToManyField(help_text='Benutzergruppen, für die dieses Feld relevant ist', to='Global.personcluster', verbose_name='Für Benutzergruppen'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('T', 'Text'), ('L', 'Langer Text'), ('N', 'Zahl'), ('D', 'Datum'), ('B', 'Wahrheitswert'), ('E', 'E-Mail'), ('P', 'Telefon'), ('C', 'Auswahl')], default='T', help_text='Art der Daten, die in diesem Feld gespeichert werden', max_length=1, verbose_name='Datentyp'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_for_choices',
            field=models.CharField(blank=True, help_text='Nur für Datentyp "Auswahl": Kommagetrennte Optionen, z.B. "Vegan, Vegetarisch, Konventionell"', max_length=250, null=True, verbose_name='Auswahloptionen'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Ausführliche Beschreibung der Aufgabe', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_art',
            field=models.ForeignKey(blank=True, help_text='Kategorie dieser Aufgabe, bestimmt den Zeitraum', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.aufgabencluster', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_monat',
            field=models.IntegerField(blank=True, help_text='Monat, in dem die Aufgabe fällig ist (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Fällig im Monat'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_tag',
            field=models.IntegerField(blank=True, help_text='Tag im Monat, an dem die Aufgabe fällig ist (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Fällig am Tag'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_tage_nach_start',
            field=models.IntegerField(blank=True, help_text='Anzahl der Tage nach Einsatzbeginn, wann die Aufgabe fällig ist', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tage nach Einsatzbeginn'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='faellig_tage_vor_ende',
            field=models.IntegerField(blank=True, help_text='Anzahl der Tage vor Einsatzende, wann die Aufgabe fällig ist', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tage vor Einsatzende'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='mitupload',
            field=models.BooleanField(default=True, help_text='Ermöglicht und erfordert das Hochladen von Dateien bei dieser Aufgabe', verbose_name='Datei-Upload erlauben'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='name',
            field=models.CharField(help_text='Name der Aufgabe', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='person_cluster',
            field=models.ManyToManyField(help_text='Benutzergruppen, für die diese Aufgabe relevant ist', to='Global.personcluster', verbose_name='Für Benutzergruppen'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='requires_submission',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, muss die Aufgabe aktiv als erledigt markiert werden', verbose_name='Bestätigung erforderlich'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='wiederholung',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird die Aufgabe regelmäßig wiederholt', verbose_name='Regelmäßige Wiederholung'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='wiederholung_ende',
            field=models.DateField(blank=True, help_text='Datum, bis zu dem die Aufgabe wiederholt wird', null=True, verbose_name='Wiederholung bis'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='wiederholung_interval_wochen',
            field=models.IntegerField(blank=True, help_text='Wiederholungsintervall in Wochen', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wiederholung alle x Wochen'),
        ),
        migrations.AlterField(
            model_name='aufgabencluster',
            name='name',
            field=models.CharField(help_text='Name der Aufgabenkategorie', max_length=50, verbose_name='Kategoriename'),
        ),
        migrations.AlterField(
            model_name='aufgabencluster',
            name='person_cluster',
            field=models.ManyToManyField(help_text='Benutzergruppen, für die diese Kategorie relevant ist', to='Global.personcluster', verbose_name='Für Benutzergruppen'),
        ),
        migrations.AlterField(
            model_name='aufgabencluster',
            name='type',
            field=models.CharField(blank=True, choices=[('V', 'Vor Einsatz'), ('W', 'Während Einsatz'), ('N', 'Nach Einsatz')], help_text='Zeitraum, in dem Aufgaben dieser Kategorie anfallen (nur für Freiwillige)', max_length=1, null=True, verbose_name='Zeitraum'),
        ),
        migrations.AlterField(
            model_name='aufgabezwischenschritte2',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung des Zwischenschritts', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='aufgabezwischenschritte2',
            name='name',
            field=models.CharField(help_text='Name des Zwischenschritts', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dokument2',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung der Datei', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='dokument2',
            name='darf_bearbeiten',
            field=models.ManyToManyField(help_text='Benutzergruppen, die diese Datei bearbeiten können', to='Global.personcluster', verbose_name='Darf bearbeiten'),
        ),
        migrations.AlterField(
            model_name='dokument2',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Datum der Erstellung der Datei', verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='dokument2',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Datum der letzten Änderung der Datei', verbose_name='Zuletzt geändert am'),
        ),
        migrations.AlterField(
            model_name='dokument2',
            name='link',
            field=models.URLField(blank=True, help_text='Link zu einer externen Datei', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='dokument2',
            name='titel',
            field=models.CharField(blank=True, help_text='Titel der Datei', max_length=100, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='einsatzland2',
            name='code',
            field=models.CharField(help_text='Zweistelliger ISO-Code des Einsatzlandes (z.B. DE, CH, AT, ...)', max_length=2, verbose_name='Einsatzland-Code'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Anonym einreichen'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='Feedback-Text'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Ausführliche Beschreibung der Aufgabe', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_art',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Kategorie dieser Aufgabe, bestimmt den Zeitraum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.aufgabencluster', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_monat',
            field=models.IntegerField(blank=True, help_text='Monat, in dem die Aufgabe fällig ist (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Fällig im Monat'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_tag',
            field=models.IntegerField(blank=True, help_text='Tag im Monat, an dem die Aufgabe fällig ist (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Fällig am Tag'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_tage_nach_start',
            field=models.IntegerField(blank=True, help_text='Anzahl der Tage nach Einsatzbeginn, wann die Aufgabe fällig ist', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tage nach Einsatzbeginn'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='faellig_tage_vor_ende',
            field=models.IntegerField(blank=True, help_text='Anzahl der Tage vor Einsatzende, wann die Aufgabe fällig ist', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tage vor Einsatzende'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='mitupload',
            field=models.BooleanField(default=True, help_text='Ermöglicht und erfordert das Hochladen von Dateien bei dieser Aufgabe', verbose_name='Datei-Upload erlauben'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='name',
            field=models.CharField(help_text='Name der Aufgabe', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='requires_submission',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, muss die Aufgabe aktiv als erledigt markiert werden', verbose_name='Bestätigung erforderlich'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='wiederholung',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird die Aufgabe regelmäßig wiederholt', verbose_name='Regelmäßige Wiederholung'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='wiederholung_ende',
            field=models.DateField(blank=True, help_text='Datum, bis zu dem die Aufgabe wiederholt wird', null=True, verbose_name='Wiederholung bis'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='wiederholung_interval_wochen',
            field=models.IntegerField(blank=True, help_text='Wiederholungsintervall in Wochen', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wiederholung alle x Wochen'),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='beschreibung',
            field=models.TextField(blank=True, help_text='Beschreibung der Datei', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datum der Erstellung der Datei', verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='date_modified',
            field=models.DateTimeField(blank=True, editable=False, help_text='Datum der letzten Änderung der Datei', verbose_name='Zuletzt geändert am'),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='link',
            field=models.URLField(blank=True, help_text='Link zu einer externen Datei', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='titel',
            field=models.CharField(blank=True, help_text='Titel der Datei', max_length=100, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='historicaleinsatzland2',
            name='code',
            field=models.CharField(help_text='Zweistelliger ISO-Code des Einsatzlandes (z.B. DE, CH, AT, ...)', max_length=2, verbose_name='Einsatzland-Code'),
        ),
        migrations.AlterField(
            model_name='historicalkalenderevent',
            name='description',
            field=models.TextField(blank=True, help_text='Ausführliche Beschreibung des Termins (optional)', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalkalenderevent',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Enddatum und -uhrzeit des Termins (optional)', null=True, verbose_name='Endet am'),
        ),
        migrations.AlterField(
            model_name='historicalkalenderevent',
            name='start',
            field=models.DateTimeField(help_text='Startdatum und -uhrzeit des Termins', verbose_name='Beginnt am'),
        ),
        migrations.AlterField(
            model_name='historicalkalenderevent',
            name='title',
            field=models.CharField(help_text='Titel des Termins', max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='historicalordner2',
            name='color',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Farbliche Markierung des Ordners', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.dokumentcolor2', verbose_name='Farbkennzeichnung'),
        ),
        migrations.AlterField(
            model_name='historicalordner2',
            name='ordner_name',
            field=models.CharField(help_text='Name des Ordners', max_length=100, verbose_name='Ordnername'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='ampel',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Ampelfunktion für diese Gruppe anzuzeigen', verbose_name='Ampel anzeigen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='aufgaben',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Aufgaben für diese Gruppe anzuzeigen', verbose_name='Aufgaben anzeigen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='bilder',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Bilder für diese Gruppe anzuzeigen', verbose_name='Bilder anzeigen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='calendar',
            field=models.BooleanField(default=False, help_text='Aktivieren, um den Kalender für diese Gruppe anzuzeigen', verbose_name='Kalender anzeigen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='dokumente',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Dokumente für diese Gruppe anzuzeigen', verbose_name='Dokumente anzeigen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='name',
            field=models.CharField(help_text='Name der Benutzergruppe, z.B. "Freiwillige 2023" oder "Teamleitung"', max_length=50, verbose_name='Benutzergruppe'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='notfallkontakt',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Notfallkontakte für diese Gruppe anzuzeigen', verbose_name='Notfallkontakt anzeigen'),
        ),
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='view',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('F', 'Freiwillige:r'), ('E', 'Ehemalige:r'), ('T', 'Team')], default='F', help_text='Bestimmt die Standardansicht für Mitglieder dieser Gruppe', max_length=1, verbose_name='Standardansicht'),
        ),
        migrations.AlterField(
            model_name='historicalpost2',
            name='text',
            field=models.TextField(help_text='Text des Posts', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='historicalpost2',
            name='title',
            field=models.CharField(help_text='Titel des Posts', max_length=50, verbose_name='Post-Titel'),
        ),
        migrations.AlterField(
            model_name='historicalpost2',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Benutzer, der den Post erstellt hat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='historicalprofiluser2',
            name='attribut',
            field=models.CharField(help_text='Attribut, das gespeichert werden soll', max_length=50, verbose_name='Attribut'),
        ),
        migrations.AlterField(
            model_name='historicalprofiluser2',
            name='value',
            field=models.TextField(help_text='Wert, der gespeichert werden soll', verbose_name='Wert'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='aufgabe',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Die zugewiesene Aufgabe', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.aufgabe2', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='benachrichtigung_cc',
            field=models.CharField(blank=True, help_text='Weitere E-Mail-Adressen, die Benachrichtigungen erhalten sollen (kommagetrennt)', max_length=255, null=True, verbose_name='E-Mail-Kopie an'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='erledigt',
            field=models.BooleanField(default=False, help_text='Zeigt an, ob die Aufgabe abgeschlossen ist', verbose_name='Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='erledigt_am',
            field=models.DateField(blank=True, help_text='Datum, an dem die Aufgabe abgeschlossen wurde', null=True, verbose_name='Abgeschlossen am'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='faellig',
            field=models.DateField(blank=True, help_text='Datum, bis zu dem die Aufgabe erledigt sein sollte', null=True, verbose_name='Fälligkeitsdatum'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='file',
            field=models.TextField(blank=True, help_text='Datei, die für diese Aufgabe hochgeladen wurde', max_length=255, null=True, verbose_name='Angehängte Datei'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='last_reminder',
            field=models.DateField(blank=True, help_text='Datum der letzten versendeten Erinnerung', null=True, verbose_name='Letzte Erinnerung'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='pending',
            field=models.BooleanField(default=False, help_text='Zeigt an, dass die Aufgabe begonnen aber noch nicht abgeschlossen wurde', verbose_name='In Bearbeitung'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='personalised_description',
            field=models.TextField(blank=True, help_text='Individuelle Anmerkungen zu dieser Aufgabe', null=True, verbose_name='Persönliche Notizen'),
        ),
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Benutzer:in, dem diese Aufgabe zugewiesen ist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in'),
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='description',
            field=models.TextField(blank=True, help_text='Ausführliche Beschreibung des Termins (optional)', null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='end',
            field=models.DateTimeField(blank=True, help_text='Enddatum und -uhrzeit des Termins (optional)', null=True, verbose_name='Endet am'),
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='start',
            field=models.DateTimeField(help_text='Startdatum und -uhrzeit des Termins', verbose_name='Beginnt am'),
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='title',
            field=models.CharField(help_text='Titel des Termins', max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='user',
            field=models.ManyToManyField(help_text='Personen, die an diesem Termin teilnehmen', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer:innen'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt2',
            name='email',
            field=models.EmailField(blank=True, help_text='E-Mail-Adresse des Notfallkontakts', max_length=100, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt2',
            name='first_name',
            field=models.CharField(help_text='Vorname des Notfallkontakts', max_length=50, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt2',
            name='last_name',
            field=models.CharField(help_text='Nachname des Notfallkontakts', max_length=50, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt2',
            name='phone',
            field=models.CharField(blank=True, help_text='Mobiltelefonnummer', max_length=20, null=True, verbose_name='Telefon (Mobil)'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt2',
            name='phone_work',
            field=models.CharField(blank=True, help_text='Geschäftliche Telefonnummer', max_length=20, null=True, verbose_name='Telefon (Arbeit)'),
        ),
        migrations.AlterField(
            model_name='notfallkontakt2',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Zugehörige:r Benutzer:in, für den dieser Notfallkontakt gilt', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in'),
        ),
        migrations.AlterField(
            model_name='ordner2',
            name='color',
            field=models.ForeignKey(blank=True, help_text='Farbliche Markierung des Ordners', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Global.dokumentcolor2', verbose_name='Farbkennzeichnung'),
        ),
        migrations.AlterField(
            model_name='ordner2',
            name='ordner_name',
            field=models.CharField(help_text='Name des Ordners', max_length=100, verbose_name='Ordnername'),
        ),
        migrations.AlterField(
            model_name='ordner2',
            name='typ',
            field=models.ManyToManyField(help_text='Benutzergruppen, die diesen Ordner sehen können', to='Global.personcluster', verbose_name='Sichtbar für'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='ampel',
            field=models.BooleanField(default=False, help_text='Aktivieren, um die Ampelfunktion für diese Gruppe anzuzeigen', verbose_name='Ampel anzeigen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='aufgaben',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Aufgaben für diese Gruppe anzuzeigen', verbose_name='Aufgaben anzeigen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='bilder',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Bilder für diese Gruppe anzuzeigen', verbose_name='Bilder anzeigen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='calendar',
            field=models.BooleanField(default=False, help_text='Aktivieren, um den Kalender für diese Gruppe anzuzeigen', verbose_name='Kalender anzeigen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='dokumente',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Dokumente für diese Gruppe anzuzeigen', verbose_name='Dokumente anzeigen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='name',
            field=models.CharField(help_text='Name der Benutzergruppe, z.B. "Freiwillige 2023" oder "Teamleitung"', max_length=50, verbose_name='Benutzergruppe'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='notfallkontakt',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Notfallkontakte für diese Gruppe anzuzeigen', verbose_name='Notfallkontakt anzeigen'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='view',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('F', 'Freiwillige:r'), ('E', 'Ehemalige:r'), ('T', 'Team')], default='F', help_text='Bestimmt die Standardansicht für Mitglieder dieser Gruppe', max_length=1, verbose_name='Standardansicht'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='text',
            field=models.TextField(help_text='Text des Posts', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='title',
            field=models.CharField(help_text='Titel des Posts', max_length=50, verbose_name='Post-Titel'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='user',
            field=models.ForeignKey(help_text='Benutzer, der den Post erstellt hat', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='profiluser2',
            name='attribut',
            field=models.CharField(help_text='Attribut, das gespeichert werden soll', max_length=50, verbose_name='Attribut'),
        ),
        migrations.AlterField(
            model_name='profiluser2',
            name='value',
            field=models.TextField(help_text='Wert, der gespeichert werden soll', verbose_name='Wert'),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Global.attribute', verbose_name='Benutzerdatenfeld'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='aufgabe',
            field=models.ForeignKey(help_text='Die zugewiesene Aufgabe', on_delete=django.db.models.deletion.CASCADE, to='Global.aufgabe2', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='benachrichtigung_cc',
            field=models.CharField(blank=True, help_text='Weitere E-Mail-Adressen, die Benachrichtigungen erhalten sollen (kommagetrennt)', max_length=255, null=True, verbose_name='E-Mail-Kopie an'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='erledigt',
            field=models.BooleanField(default=False, help_text='Zeigt an, ob die Aufgabe abgeschlossen ist', verbose_name='Abgeschlossen'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='erledigt_am',
            field=models.DateField(blank=True, help_text='Datum, an dem die Aufgabe abgeschlossen wurde', null=True, verbose_name='Abgeschlossen am'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='faellig',
            field=models.DateField(blank=True, help_text='Datum, bis zu dem die Aufgabe erledigt sein sollte', null=True, verbose_name='Fälligkeitsdatum'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='file',
            field=models.FileField(blank=True, help_text='Datei, die für diese Aufgabe hochgeladen wurde', max_length=255, null=True, upload_to='uploads/', verbose_name='Angehängte Datei'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='last_reminder',
            field=models.DateField(blank=True, help_text='Datum der letzten versendeten Erinnerung', null=True, verbose_name='Letzte Erinnerung'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='pending',
            field=models.BooleanField(default=False, help_text='Zeigt an, dass die Aufgabe begonnen aber noch nicht abgeschlossen wurde', verbose_name='In Bearbeitung'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='personalised_description',
            field=models.TextField(blank=True, help_text='Individuelle Anmerkungen zu dieser Aufgabe', null=True, verbose_name='Persönliche Notizen'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='user',
            field=models.ForeignKey(help_text='Benutzer:in, dem diese Aufgabe zugewiesen ist', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in'),
        ),
    ]
