# Generated by Django 6.0.6 on 2026-07-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0031_alter_ampelconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampelconfiguration',
            name='reminder_end_date',
            field=models.DateField(blank=True, help_text='Bis zu diesem Datum werden Erinnerungen gesendet. Leer = kein Enddatum.', null=True, verbose_name='Erinnerungen bis'),
        ),
        migrations.AlterField(
            model_name='ampelconfiguration',
            name='reminder_start_date',
            field=models.DateField(blank=True, help_text='Ab diesem Datum werden Erinnerungen gesendet. Leer = kein Startdatum.', null=True, verbose_name='Erinnerungen ab'),
        ),
    ]
