# Generated by Django 5.1.2 on 2025-04-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0031_alter_attribute_options_and_more'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost2',
            name='has_survey',
            field=models.BooleanField(default=False, help_text='Post enthält eine Umfrage', verbose_name='Umfrage'),
        ),
        migrations.AddField(
            model_name='post2',
            name='has_survey',
            field=models.BooleanField(default=False, help_text='Post enthält eine Umfrage', verbose_name='Umfrage'),
        ),
        migrations.AlterField(
            model_name='aufgabe2',
            name='requires_submission',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, wird die Aufgabe nach Erledigung als pending markiert und muss manuell als erledigt bestätigt werden', verbose_name='Bestätigung erforderlich'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='requires_submission',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, wird die Aufgabe nach Erledigung als pending markiert und muss manuell als erledigt bestätigt werden', verbose_name='Bestätigung erforderlich'),
        ),
        migrations.CreateModel(
            name='PostSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text='Text der Umfragefrage', max_length=200, verbose_name='Frage')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question', to='Global.post2', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Umfragefrage',
                'verbose_name_plural': 'Umfragefragen',
            },
        ),
        migrations.CreateModel(
            name='PostSurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(help_text='Text der Antwortmöglichkeit', max_length=100, verbose_name='Antwort')),
                ('votes', models.IntegerField(default=0, help_text='Anzahl der Stimmen für diese Antwort', verbose_name='Anzahl Stimmen')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='Global.postsurveyquestion', verbose_name='Frage')),
            ],
            options={
                'verbose_name': 'Umfrageantwort',
                'verbose_name_plural': 'Umfrageantworten',
            },
        ),
    ]
