# Generated by Django 6.0.6 on 2026-08-27

from django.db import migrations, models

import Global.models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0032_ampelconfiguration_date_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument2',
            name='preview_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=Global.models.upload_to_preview_image),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='preview_image',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
