# Generated by Django 5.1.2 on 2025-04-11 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0032_historicalpost2_has_survey_post2_has_survey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsurveyanswer',
            name='votes',
        ),
        migrations.AddField(
            model_name='postsurveyanswer',
            name='votes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer, die an der Umfrage teilgenommen haben'),
        ),
    ]
