# Generated by Django 5.1.2 on 2025-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0033_remove_postsurveyanswer_votes_postsurveyanswer_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersoncluster',
            name='posts',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Posts für diese Gruppe anzuzeigen', verbose_name='Posts anzeigen'),
        ),
        migrations.AddField(
            model_name='personcluster',
            name='posts',
            field=models.BooleanField(default=False, help_text='Aktivieren, um Posts für diese Gruppe anzuzeigen', verbose_name='Posts anzeigen'),
        ),
    ]
