# Generated by Django 5.1.2 on 2025-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0034_historicalpersoncluster_posts_personcluster_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='person_cluster',
            field=models.ManyToManyField(blank=True, help_text='Benutzergruppen, für die dieser Post relevant ist', to='Global.personcluster', verbose_name='Für Benutzergruppen'),
        ),
    ]
