# Generated by Django 5.1.2 on 2025-04-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0035_post2_person_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluseraufgaben',
            name='file_list',
            field=models.JSONField(blank=True, help_text='Dateien, die für diese Aufgabe hochgeladen wurden', null=True, verbose_name='Angehängte Dateien'),
        ),
        migrations.AddField(
            model_name='useraufgaben',
            name='file_list',
            field=models.JSONField(blank=True, help_text='Dateien, die für diese Aufgabe hochgeladen wurden', null=True, verbose_name='Angehängte Dateien'),
        ),
    ]
