# Generated by Django 5.1.2 on 2025-04-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0036_historicaluseraufgaben_file_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluseraufgaben',
            name='pending',
            field=models.BooleanField(default=False, help_text='Zeigt an, dass die Aufgabe begonnen aber noch nicht abgeschlossen wurde', verbose_name='Pending'),
        ),
        migrations.AlterField(
            model_name='useraufgaben',
            name='pending',
            field=models.BooleanField(default=False, help_text='Zeigt an, dass die Aufgabe begonnen aber noch nicht abgeschlossen wurde', verbose_name='Pending'),
        ),
    ]
