# Generated by Django 5.1.2 on 2025-04-12 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0037_alter_historicaluseraufgaben_pending_and_more'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.personcluster', verbose_name='Person Cluster'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push subscription endpoint URL', max_length=500)),
                ('p256dh', models.CharField(help_text="User's public key for encryption", max_length=255)),
                ('auth', models.CharField(help_text='Authentication secret', max_length=255)),
                ('name', models.CharField(blank=True, help_text='Optional name for this device/browser', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this subscription was created')),
                ('last_used', models.DateTimeField(blank=True, help_text='When this subscription was last used successfully', null=True)),
                ('org', models.ForeignKey(help_text='Organization the user belongs to', on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('user', models.ForeignKey(help_text='User who has subscribed to push notifications', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push-Abonnement',
                'verbose_name_plural': 'Push-Abonnements',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
