# Generated by Django 5.1.2 on 2025-04-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0038_alter_customuser_person_cluster_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.CharField(help_text='Authentication secret', max_length=500),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for this device/browser', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.CharField(help_text="User's public key for encryption", max_length=500),
        ),
    ]
