# Generated by Django 5.1.2 on 2025-05-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0039_alter_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Global.personcluster', verbose_name='Benutzergruppe'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='person_cluster',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.personcluster', verbose_name='Benutzergruppe'),
        ),
    ]
