# Generated by Django 5.2.1 on 2025-05-15 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0040_alter_customuser_person_cluster_and_more'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EinsatzstelleNotiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notiz', models.TextField(blank=True, help_text='Notiz der Einsatzstelle', null=True, verbose_name='Notiz')),
                ('einsatzstelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Global.einsatzstelle2', verbose_name='Einsatzstelle')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Einsatzstellen Notiz',
                'verbose_name_plural': 'Einsatzstellen Notizen',
            },
        ),
    ]
