# Generated by Django 5.2.1 on 2025-05-15 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0041_einsatzstellenotiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzstellenotiz',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Erstellt am'),
            preserve_default=False,
        ),
    ]
