# Generated by Django 5.2.1 on 2025-05-15 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0042_einsatzstellenotiz_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalkalenderevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Kalender-Termin', 'verbose_name_plural': 'historical Kalender-Termine'},
        ),
        migrations.AlterModelOptions(
            name='kalenderevent',
            options={'verbose_name': 'Kalender-Termin', 'verbose_name_plural': 'Kalender-Termine'},
        ),
        migrations.AlterField(
            model_name='historicalkalenderevent',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enddatum und -uhrzeit des Termins (optional)', verbose_name='Endet am'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enddatum und -uhrzeit des Termins (optional)', verbose_name='Endet am'),
            preserve_default=False,
        ),
    ]
