# Generated by Django 5.2.1 on 2025-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0043_alter_historicalkalenderevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkalenderevent',
            name='end',
            field=models.DateTimeField(help_text='Enddatum und -uhrzeit des Termins', verbose_name='Endet am'),
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='end',
            field=models.DateTimeField(help_text='Enddatum und -uhrzeit des Termins', verbose_name='Endet am'),
        ),
    ]
