# Generated by Django 5.2.1 on 2025-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0044_alter_historicalkalenderevent_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersoncluster',
            name='view',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('F', 'Freiwillige:r'), ('E', 'Ehemalige:r'), ('T', 'Team'), ('B', 'Bewerber:in')], default='F', help_text='Bestimmt die Standardansicht für Mitglieder dieser Gruppe', max_length=1, verbose_name='Standardansicht'),
        ),
        migrations.AlterField(
            model_name='personcluster',
            name='view',
            field=models.CharField(choices=[('A', 'Admin'), ('O', 'Organisation'), ('F', 'Freiwillige:r'), ('E', 'Ehemalige:r'), ('T', 'Team'), ('B', 'Bewerber:in')], default='F', help_text='Bestimmt die Standardansicht für Mitglieder dieser Gruppe', max_length=1, verbose_name='Standardansicht'),
        ),
    ]
