# Generated by Django 5.2.1 on 2025-05-22 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0046_alter_userattribute_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe2',
            name='repeat_push_days',
            field=models.IntegerField(default=7, help_text='Anzahl der Tage, die gewartet wird, bevor eine neue Benachrichtigung für eine nicht erledigte Aufgabe gesendet wird', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wartezeit bis nächste Benachrichtigung'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe2',
            name='repeat_push_days',
            field=models.IntegerField(default=7, help_text='Anzahl der Tage, die gewartet wird, bevor eine neue Benachrichtigung für eine nicht erledigte Aufgabe gesendet wird', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wartezeit bis nächste Benachrichtigung'),
        ),
    ]
