# Generated by Django 5.2.1 on 2025-05-26 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0047_aufgabe2_repeat_push_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kalenderevent',
            name='mail_reminder_sent_to',
            field=models.ManyToManyField(help_text='Personen, an die eine Mail-Erinnerung gesendet wurde', related_name='calendar_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Mail-Erinnerung gesendet an'),
        ),
        migrations.AlterField(
            model_name='kalenderevent',
            name='user',
            field=models.ManyToManyField(help_text='Personen, die an diesem Termin teilnehmen', related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer:innen'),
        ),
    ]
