# Generated by Django 5.2.1 on 2025-05-26 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0048_kalenderevent_mail_reminder_sent_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalenderevent',
            name='mail_reminder_sent_to',
            field=models.ManyToManyField(blank=True, help_text='Personen, an die eine Mail-Erinnerung gesendet wurde', null=True, related_name='calendar_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Mail-Erinnerung gesendet an'),
        ),
    ]
