# Generated by Django 5.2.1 on 2025-05-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0050_alter_kalenderevent_mail_reminder_sent_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzstellenotiz',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Angeheftet'),
        ),
    ]
