# Generated by Django 5.2.1 on 2025-05-27 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0051_einsatzstellenotiz_pinned'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notiz', models.TextField(blank=True, help_text='Notiz', null=True, verbose_name='Notiz')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('pinned', models.BooleanField(default=False, verbose_name='Angeheftet')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Sticky Note',
                'verbose_name_plural': 'Sticky Notes',
            },
        ),
    ]
