# Generated by Django 5.2.1 on 2025-05-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0052_stickynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='notiz',
            field=models.CharField(blank=True, help_text='Notiz', max_length=1000, null=True, verbose_name='Notiz'),
        ),
    ]
