# Generated by Django 5.2.1 on 2025-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0053_alter_stickynote_notiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='priority',
            field=models.IntegerField(default=0, help_text='Priorität der Notiz', verbose_name='Priorität'),
        ),
    ]
