# Generated by Django 5.2.1 on 2025-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0054_stickynote_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersoncluster',
            name='token',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=512, null=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='personcluster',
            name='token',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=512, null=True, verbose_name='Token'),
        ),
    ]
