# Generated by Django 5.2.1 on 2025-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0055_historicalpersoncluster_token_personcluster_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpersoncluster',
            name='token',
        ),
        migrations.RemoveField(
            model_name='personcluster',
            name='token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=512, null=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='token',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=512, null=True, verbose_name='Token'),
        ),
    ]
