# Generated by Django 5.2.1 on 2025-06-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0056_remove_historicalpersoncluster_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calendar_token',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=512, null=True, verbose_name='Kalender-Token'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='calendar_token',
            field=models.CharField(blank=True, help_text='Wird automatisch erzeugt, wenn leer', max_length=512, null=True, verbose_name='Kalender-Token'),
        ),
    ]
