# Generated by Django 5.2.2 on 2025-06-17 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0057_customuser_calendar_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useraufgaben',
            name='file_downloaded_of',
            field=models.ManyToManyField(blank=True, help_text='Benutzer, die die Dateien heruntergeladen haben', null=True, related_name='file_downloaded_of', to=settings.AUTH_USER_MODEL, verbose_name='Dateien heruntergeladen von'),
        ),
    ]
