# Generated by Django 5.2.2 on 2025-06-21 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0058_useraufgaben_file_downloaded_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraufgaben',
            name='file_downloaded_of',
            field=models.ManyToManyField(blank=True, help_text='Benutzer, die die Dateien heruntergeladen haben', related_name='file_downloaded_of', to=settings.AUTH_USER_MODEL, verbose_name='Dateien heruntergeladen von'),
        ),
    ]
