# Generated by Django 5.2.2 on 2025-07-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0059_alter_useraufgaben_file_downloaded_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzstelle2',
            name='max_freiwillige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximale Anzahl Freiwillige'),
        ),
        migrations.AddField(
            model_name='historicaleinsatzstelle2',
            name='max_freiwillige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximale Anzahl Freiwillige'),
        ),
    ]
