# Generated by Django 5.2.2 on 2025-07-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0060_einsatzstelle2_max_freiwillige_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einsatzstelle2',
            name='max_freiwillige',
        ),
        migrations.RemoveField(
            model_name='historicaleinsatzstelle2',
            name='max_freiwillige',
        ),
    ]
