# Generated by Django 5.2.2 on 2025-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0063_remove_einsatzstelle2_max_freiwillige_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einsatzstelle2',
            name='max_freiwillige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximale Anzahl Freiwillige'),
        ),
        migrations.AddField(
            model_name='historicaleinsatzstelle2',
            name='max_freiwillige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximale Anzahl Freiwillige'),
        ),
    ]
