# Generated by Django 5.2.2 on 2025-07-31 20:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0064_einsatzstelle2_max_freiwillige_and_more'),
        ('ORG', '0034_dokumentcolor_historicaldokumentcolor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BilderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Kommentar')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('bilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Global.bilder2', verbose_name='Bild')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Bildkommentar',
                'verbose_name_plural': 'Bildkommentare',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBilderComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Kommentar')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Erstellt am')),
                ('date_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Aktualisiert am')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bilder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.bilder2', verbose_name='Bild')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'historical Bildkommentar',
                'verbose_name_plural': 'historical Bildkommentare',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBilderReaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Daumen hoch'), ('❤️', 'Herz'), ('😂', 'Lachen'), ('😮', 'Überrascht'), ('😢', 'Traurig'), ('😡', 'Wütend')], max_length=10, verbose_name='Emoji')),
                ('date_created', models.DateTimeField(blank=True, editable=False, verbose_name='Erstellt am')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bilder', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Global.bilder2', verbose_name='Bild')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'historical Bildreaktion',
                'verbose_name_plural': 'historical Bildreaktionen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BilderReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Daumen hoch'), ('❤️', 'Herz'), ('😂', 'Lachen'), ('😮', 'Überrascht'), ('😢', 'Traurig'), ('😡', 'Wütend')], max_length=10, verbose_name='Emoji')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('bilder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='Global.bilder2', verbose_name='Bild')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Bildreaktion',
                'verbose_name_plural': 'Bildreaktionen',
                'unique_together': {('bilder', 'user', 'emoji')},
            },
        ),
    ]
