# Generated by Django 5.2.2 on 2025-07-31 21:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0065_bildercomment_historicalbildercomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bilderreaction',
            unique_together={('bilder', 'user')},
        ),
    ]
