# Generated by Django 5.2.2 on 2025-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0066_alter_bilderreaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument2',
            name='titel',
            field=models.CharField(blank=True, help_text='Titel der Datei', max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='historicaldokument2',
            name='titel',
            field=models.CharField(blank=True, help_text='Titel der Datei', max_length=255, null=True, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='historicalordner2',
            name='ordner_name',
            field=models.CharField(help_text='Name des Ordners', max_length=255, verbose_name='Ordnername'),
        ),
        migrations.AlterField(
            model_name='ordner2',
            name='ordner_name',
            field=models.CharField(help_text='Name des Ordners', max_length=255, verbose_name='Ordnername'),
        ),
    ]
