# Generated by Django 5.2.2 on 2025-08-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0067_alter_dokument2_titel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Ist online'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt online'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Ist online'),
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt online'),
        ),
    ]
