# Generated by Django 5.2.2 on 2025-08-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0068_customuser_is_online_customuser_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einsatzland2',
            options={'ordering': ['name', 'code'], 'verbose_name': 'Einsatzland', 'verbose_name_plural': 'Einsatzländer'},
        ),
    ]
