# Generated by Django 5.2.2 on 2025-09-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0069_alter_einsatzland2_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabe2',
            name='mitupload',
            field=models.BooleanField(default=True, help_text='Ermöglicht und erfordert das Hochladen von Dateien bei dieser Aufgabe', verbose_name='Datei-Upload erforderlich'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabe2',
            name='mitupload',
            field=models.BooleanField(default=True, help_text='Ermöglicht und erfordert das Hochladen von Dateien bei dieser Aufgabe', verbose_name='Datei-Upload erforderlich'),
        ),
    ]
