# Generated by Django 5.2.2 on 2025-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0070_alter_aufgabe2_mitupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabe2',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optionale Datei als Anhang für diese Aufgabe', null=True, upload_to='aufgaben_attachments/', verbose_name='Anhang'),
        ),
        migrations.AddField(
            model_name='historicalaufgabe2',
            name='attachment',
            field=models.TextField(blank=True, help_text='Optionale Datei als Anhang für diese Aufgabe', max_length=100, null=True, verbose_name='Anhang'),
        ),
    ]
