# Generated by Django 5.2.2 on 2025-08-08 17:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('TEAM', '0001_initial'), ('TEAM', '0002_alter_team_land'), ('TEAM', '0003_alter_team_land')]

    initial = True

    dependencies = [
        ('Global', '0024_remove_referenten2_land_remove_referenten2_org_and_more'),
        ('Global', '0026_remove_historicalordner2_typ_remove_ordner2_typ_and_more'),
        ('Global', '0027_aufgabencluster_faellig_art'),
        ('ORG', '0032_remove_referentenaufgaben_aufgabe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTeam',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
            ],
            options={
                'verbose_name': 'historical Teammitglied',
                'verbose_name_plural': 'historical Team',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.ManyToManyField(blank=True, to='Global.einsatzland2', verbose_name='Länderzuständigkeit')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation', verbose_name='Organisation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer:in')),
            ],
            options={
                'verbose_name': 'Teammitglied',
                'verbose_name_plural': 'Team',
            },
        ),
    ]
