# Generated by Django 6.0.3 on 2026-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='aufgabenuebersicht',
            field=models.CharField(choices=[('N', 'Keine Aufgabenübersicht'), ('L', 'Aufgabenübersicht für Freiwillige mit gleichem Einsatzland'), ('A', 'Aufgabenübersicht für alle Freiwillige')], default='N', help_text='Aufgabenübersicht, die für dieses Teammitglied angezeigt werden', max_length=1, verbose_name='Aufgabenübersicht'),
        ),
        migrations.AddField(
            model_name='team',
            name='aufgabenuebersicht',
            field=models.CharField(choices=[('N', 'Keine Aufgabenübersicht'), ('L', 'Aufgabenübersicht für Freiwillige mit gleichem Einsatzland'), ('A', 'Aufgabenübersicht für alle Freiwillige')], default='N', help_text='Aufgabenübersicht, die für dieses Teammitglied angezeigt werden', max_length=1, verbose_name='Aufgabenübersicht'),
        ),
    ]
