# Generated by Django 5.1.2 on 2025-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0026_remove_historicalordner2_typ_remove_ordner2_typ_and_more'),
        ('TEAM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='land',
            field=models.ManyToManyField(to='Global.einsatzland2', verbose_name='Länderzuständigkeit'),
        ),
    ]
