# Generated by Django 5.1.2 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM', '0001_initial'),
        ('Global', '0020_dokumentcolor2_organisation2_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='land',
            field=models.ManyToManyField(blank=True, null=True, to='Global.einsatzland2', verbose_name='Länderzuständigkeit'),
        ),
    ]
