# Generated by Django 5.1.2 on 2025-04-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global', '0027_aufgabencluster_faellig_art'),
        ('TEAM', '0002_alter_team_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='land',
            field=models.ManyToManyField(blank=True, to='Global.Einsatzland2', verbose_name='Länderzuständigkeit'),
        ),
    ]
