# Generated by Django 6.0.3 on 2026-03-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAM', '0002_historicalteam_aufgabenuebersicht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalteam',
            name='aufgabenuebersicht',
            field=models.CharField(choices=[('N', 'Keine'), ('L', 'Nur für Freiwillige im Einsatzland des Teammitglieds'), ('A', 'Für alle Freiwillige')], default='N', help_text='Legt fest, für welche Freiwillige diesem Teammitglied Aufgaben angezeigt werden', max_length=1, verbose_name='Aufgabenübersicht'),
        ),
        migrations.AlterField(
            model_name='team',
            name='aufgabenuebersicht',
            field=models.CharField(choices=[('N', 'Keine'), ('L', 'Nur für Freiwillige im Einsatzland des Teammitglieds'), ('A', 'Für alle Freiwillige')], default='N', help_text='Legt fest, für welche Freiwillige diesem Teammitglied Aufgaben angezeigt werden', max_length=1, verbose_name='Aufgabenübersicht'),
        ),
    ]
