# Generated by Django 5.1.2 on 2025-01-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dokument',
            name='titel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
