# Generated by Django 6.0.4 on 2026-06-19 09:03

import uuid
from django.db import migrations, models


def populate_historical_uuids(apps, schema_editor):
    HistoricalOrganisation = apps.get_model('ORG', 'HistoricalOrganisation')
    for obj in HistoricalOrganisation.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0002_organisation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(populate_historical_uuids, migrations.RunPython.noop),
    ]
