# Generated by Django 5.1.2 on 2025-01-14 17:32

import ORG.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0002_dokument_date_modified_dokument_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='dokument',
            field=models.FileField(blank=True, null=True, upload_to=ORG.models.upload_to_folder),
        ),
    ]
