# Generated by Django 5.1.2 on 2025-01-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0003_dokument_link_alter_dokument_dokument'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='fw_darf_bearbeiten',
            field=models.BooleanField(default=True),
        ),
    ]
