# Generated by Django 5.1.2 on 2025-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0004_dokument_fw_darf_bearbeiten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
