# Generated by Django 5.1.2 on 2025-01-30 07:25

import ORG.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0005_alter_organisation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=ORG.models.upload_to_preview_image),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(default=1, upload_to='logos/'),
            preserve_default=False,
        ),
    ]
