# Generated by Django 5.1.2 on 2025-01-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FW', '0029_alter_einsatzstelle_land_alter_freiwilliger_email_and_more'),
        ('ORG', '0010_alter_referenten_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenten',
            name='land',
            field=models.ManyToManyField(blank=True, null=True, to='FW.einsatzland', verbose_name='Einsatzland'),
        ),
    ]
