# Generated by Django 5.1.2 on 2025-02-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0011_alter_referenten_land'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenten',
            options={'verbose_name': 'Länderreferent:in', 'verbose_name_plural': 'Länderreferent:innen'},
        ),
    ]
