# Generated by Django 5.1.2 on 2025-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0012_alter_referenten_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referenten',
            name='phone',
        ),
        migrations.AddField(
            model_name='referenten',
            name='phone_mobil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Mobil'),
        ),
        migrations.AddField(
            model_name='referenten',
            name='phone_work',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Arbeit'),
        ),
    ]
