# Generated by Django 5.1.2 on 2025-02-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0013_remove_referenten_phone_referenten_phone_mobil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JahrgangTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jahrgangstyp')),
            ],
            options={
                'verbose_name': 'Jahrgangstyp',
                'verbose_name_plural': 'Jahrgangstypen',
            },
        ),
        migrations.AddField(
            model_name='ordner',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.jahrgangtyp', verbose_name='Typ'),
        ),
    ]
