# Generated by Django 5.1.2 on 2025-02-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0014_jahrgangtyp_ordner_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='jahrgangtyp',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation'),
            preserve_default=False,
        ),
    ]
