# Generated by Django 5.1.2 on 2025-02-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0015_jahrgangtyp_org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenten',
            options={'verbose_name': 'Teammitglied', 'verbose_name_plural': 'Team'},
        ),
    ]
