# Generated by Django 5.1.2 on 2025-02-12 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0016_alter_referenten_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Oxford Blue')),
                ('color', models.CharField(default='#001B2E', max_length=7)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
        ),
    ]
