# Generated by Django 5.1.2 on 2025-02-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0017_dokumentcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordner',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.dokumentcolor', verbose_name='Farbe'),
        ),
    ]
