# Generated by Django 5.1.2 on 2025-02-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0018_ordner_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumentcolor',
            name='org',
        ),
        migrations.AlterField(
            model_name='dokumentcolor',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Farbcodes'),
        ),
        migrations.AlterField(
            model_name='dokumentcolor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Farbname'),
        ),
    ]
