# Generated by Django 5.1.2 on 2025-02-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0019_remove_dokumentcolor_org_alter_dokumentcolor_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(upload_to='media/logos/'),
        ),
    ]
