# Generated by Django 5.1.2 on 2025-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0020_alter_organisation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(upload_to='logos/'),
        ),
    ]
