# Generated by Django 5.1.2 on 2025-02-26 09:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0022_historicaldokument_historicaldokumentcolor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AufgabenTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Titel')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('faellig', models.DateField(verbose_name='Fällig am')),
                ('erledigt', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('erledigt_am', models.DateField(blank=True, null=True, verbose_name='Erledigt am')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Teammitglieder')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAufgabenTeam',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titel', models.CharField(max_length=50, verbose_name='Titel')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung')),
                ('faellig', models.DateField(verbose_name='Fällig am')),
                ('erledigt', models.BooleanField(default=False, verbose_name='Erledigt')),
                ('erledigt_am', models.DateField(blank=True, null=True, verbose_name='Erledigt am')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'historical aufgaben team',
                'verbose_name_plural': 'historical aufgaben teams',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
