# Generated by Django 5.1.2 on 2025-02-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0023_aufgabenteam_historicalaufgabenteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aufgabenteam',
            old_name='titel',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalaufgabenteam',
            old_name='titel',
            new_name='name',
        ),
    ]
