# Generated by Django 5.1.2 on 2025-02-26 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0024_rename_titel_aufgabenteam_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aufgabenteam',
            options={'verbose_name': 'Team Aufgabe', 'verbose_name_plural': 'Team Aufgaben'},
        ),
        migrations.AlterModelOptions(
            name='historicalaufgabenteam',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Team Aufgabe', 'verbose_name_plural': 'historical Team Aufgaben'},
        ),
        migrations.AlterField(
            model_name='aufgabenteam',
            name='user',
            field=models.ManyToManyField(help_text='Nur Organisations- und Team-Mitglieder können ausgewählt werden', to=settings.AUTH_USER_MODEL, verbose_name='Teammitglieder'),
        ),
    ]
