# Generated by Django 5.1.2 on 2025-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0025_alter_aufgabenteam_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aufgabenteam',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='historicalaufgabenteam',
            name='beschreibung',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
    ]
