# Generated by Django 5.1.2 on 2025-02-28 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0026_alter_aufgabenteam_beschreibung_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aufgabenteam',
            name='erledigt_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erledigte_aufgaben', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von'),
        ),
        migrations.AddField(
            model_name='historicalaufgabenteam',
            name='erledigt_von',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von'),
        ),
        migrations.AlterField(
            model_name='aufgabenteam',
            name='user',
            field=models.ManyToManyField(help_text='Nur Organisations- und Team-Mitglieder können ausgewählt werden', related_name='team_aufgaben', to=settings.AUTH_USER_MODEL, verbose_name='Teammitglieder'),
        ),
    ]
