# Generated by Django 5.1.2 on 2025-03-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0027_aufgabenteam_erledigt_von_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalaufgabenteam',
            name='erledigt_von',
        ),
        migrations.RemoveField(
            model_name='historicalaufgabenteam',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalaufgabenteam',
            name='org',
        ),
        migrations.DeleteModel(
            name='AufgabenTeam',
        ),
        migrations.DeleteModel(
            name='HistoricalAufgabenTeam',
        ),
    ]
