# Generated by Django 5.1.2 on 2025-03-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0028_remove_historicalaufgabenteam_erledigt_von_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorganisation',
            name='text_color_on_org_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='organisation',
            name='text_color_on_org_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
