# Generated by Django 5.1.2 on 2025-03-19 09:53

import ORG.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0029_historicalorganisation_text_color_on_org_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='dokument',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=ORG.models.upload_to_folder),
        ),
        migrations.AlterField(
            model_name='historicaldokument',
            name='dokument',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
