# Generated by Django 5.1.2 on 2025-03-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0031_historicalreferentenaufgaben_referentenaufgaben'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referentenaufgaben',
            name='aufgabe',
        ),
        migrations.RemoveField(
            model_name='referentenaufgaben',
            name='referent',
        ),
        migrations.DeleteModel(
            name='HistoricalReferentenAufgaben',
        ),
        migrations.DeleteModel(
            name='ReferentenAufgaben',
        ),
    ]
