# Generated by Django 5.1.2 on 2025-04-11 14:33

import ORG.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORG', '0033_remove_ordner_color_remove_historicalordner_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Farbname')),
                ('color', models.CharField(max_length=7, verbose_name='Farbcodes')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDokumentColor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Farbname')),
                ('color', models.CharField(max_length=7, verbose_name='Farbcodes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dokument color',
                'verbose_name_plural': 'historical dokument colors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalJahrgangTyp',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jahrgangstyp')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'historical Jahrgangstyp',
                'verbose_name_plural': 'historical Jahrgangstypen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalReferenten',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone_work', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Arbeit')),
                ('phone_mobil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Mobil')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Teammitglied',
                'verbose_name_plural': 'historical Team',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='JahrgangTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jahrgangstyp')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Jahrgangstyp',
                'verbose_name_plural': 'Jahrgangstypen',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrdner',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ordner_name', models.CharField(max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('color', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.dokumentcolor', verbose_name='Farbe')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation')),
                ('typ', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.jahrgangtyp', verbose_name='Typ')),
            ],
            options={
                'verbose_name': 'historical ordner',
                'verbose_name_plural': 'historical ordners',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MailBenachrichtigungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betreff', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
            ],
            options={
                'verbose_name': 'Mail Benachrichtigung',
                'verbose_name_plural': 'Mail Benachrichtigungen',
            },
        ),
        migrations.CreateModel(
            name='Ordner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordner_name', models.CharField(max_length=100)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.dokumentcolor', verbose_name='Farbe')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORG.jahrgangtyp', verbose_name='Typ')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDokument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dokument', models.TextField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False)),
                ('date_modified', models.DateTimeField(blank=True, editable=False)),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('fw_darf_bearbeiten', models.BooleanField(default=True)),
                ('preview_image', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.organisation')),
                ('ordner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ORG.ordner')),
            ],
            options={
                'verbose_name': 'historical dokument',
                'verbose_name_plural': 'historical dokuments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.FileField(blank=True, max_length=255, null=True, upload_to=ORG.models.upload_to_folder)),
                ('link', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('fw_darf_bearbeiten', models.BooleanField(default=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=ORG.models.upload_to_preview_image)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('ordner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.ordner')),
            ],
        ),
        migrations.CreateModel(
            name='Referenten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone_work', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Arbeit')),
                ('phone_mobil', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Mobil')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORG.organisation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teammitglied',
                'verbose_name_plural': 'Team',
            },
        ),
    ]
